#version 430 core
layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

//预览纹理
layout(binding = 0, r16_snorm) readonly uniform image3D u_PreviewTexture;

//标记纹理
layout(binding = 1, r8ui) writeonly uniform uimage3D u_MarkTexture;

//参数
uniform ivec3 u_VolumeSize;
uniform float u_MinHU;
uniform float u_MaxHU;
uniform uint u_MarkValue;

//常量
const float MAX_16BIT_SIGNED = 32767.0;


void main()
{
    ivec3 voxelCoord = ivec3(gl_GlobalInvocationID);    
    if (voxelCoord.x >= u_VolumeSize.x || voxelCoord.y >= u_VolumeSize.y || voxelCoord.z >= u_VolumeSize.z)
    {
        return;
    }
    
    float huValue = imageLoad(u_PreviewTexture, voxelCoord).r * MAX_16BIT_SIGNED;    
    if (huValue >= u_MinHU && huValue <= u_MaxHU)
    {
        imageStore(u_MarkTexture, voxelCoord, uvec4(u_MarkValue, 0, 0, 0));
    }
}
