<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <Description>MedicalSharp OpenCL算法</Description>
  </PropertyGroup>

  <ItemGroup>
    <None Update="Kernels\*.cl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.Core" Version="2.23.0" />
    <PackageReference Include="Silk.NET.OpenCL" Version="2.23.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MedicalSharp.Primitives\MedicalSharp.Primitives.csproj" />
  </ItemGroup>
</Project>
