<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <Description>MedicalSharp 渲染引擎</Description>
  </PropertyGroup>

  <ItemGroup>
    <None Update="Resources\GLSLs\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Protocols\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenTK.Graphics" Version="4.9.4" />
    <PackageReference Include="SkiaSharp" Version="3.119.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MedicalSharp.Primitives\MedicalSharp.Primitives.csproj" />
  </ItemGroup>
</Project>
