//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace itk.simple {

public class BinaryErodeImageFilter : ImageFilter {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal BinaryErodeImageFilter(global::System.IntPtr cPtr, bool cMemoryOwn) : base(SimpleITKPINVOKE.BinaryErodeImageFilter_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(BinaryErodeImageFilter obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(BinaryErodeImageFilter obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SimpleITKPINVOKE.delete_BinaryErodeImageFilter(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public BinaryErodeImageFilter() : this(SimpleITKPINVOKE.new_BinaryErodeImageFilter(), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetKernelRadius(VectorUInt32 KernelRadius) {
    SimpleITKPINVOKE.BinaryErodeImageFilter_SetKernelRadius__SWIG_0(swigCPtr, VectorUInt32.getCPtr(KernelRadius));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetKernelRadius(uint value) {
    SimpleITKPINVOKE.BinaryErodeImageFilter_SetKernelRadius__SWIG_1(swigCPtr, value);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorUInt32 GetKernelRadius() {
    VectorUInt32 ret = new VectorUInt32(SimpleITKPINVOKE.BinaryErodeImageFilter_GetKernelRadius(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetKernelType(KernelEnum KernelType) {
    SimpleITKPINVOKE.BinaryErodeImageFilter_SetKernelType(swigCPtr, KernelType.swigValue);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public KernelEnum GetKernelType() {
    KernelEnum ret = KernelEnum.swigToEnum(SimpleITKPINVOKE.BinaryErodeImageFilter_GetKernelType(swigCPtr));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetBackgroundValue(double BackgroundValue) {
    SimpleITKPINVOKE.BinaryErodeImageFilter_SetBackgroundValue(swigCPtr, BackgroundValue);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetBackgroundValue() {
    double ret = SimpleITKPINVOKE.BinaryErodeImageFilter_GetBackgroundValue(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetForegroundValue(double ForegroundValue) {
    SimpleITKPINVOKE.BinaryErodeImageFilter_SetForegroundValue(swigCPtr, ForegroundValue);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetForegroundValue() {
    double ret = SimpleITKPINVOKE.BinaryErodeImageFilter_GetForegroundValue(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetBoundaryToForeground(bool BoundaryToForeground) {
    SimpleITKPINVOKE.BinaryErodeImageFilter_SetBoundaryToForeground(swigCPtr, BoundaryToForeground);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void BoundaryToForegroundOn() {
    SimpleITKPINVOKE.BinaryErodeImageFilter_BoundaryToForegroundOn(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void BoundaryToForegroundOff() {
    SimpleITKPINVOKE.BinaryErodeImageFilter_BoundaryToForegroundOff(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool GetBoundaryToForeground() {
    bool ret = SimpleITKPINVOKE.BinaryErodeImageFilter_GetBoundaryToForeground(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string GetName() {
    string ret = SimpleITKPINVOKE.BinaryErodeImageFilter_GetName(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string ToString() {
    string ret = SimpleITKPINVOKE.BinaryErodeImageFilter_ToString(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Image Execute(Image image1) {
    Image ret = new Image(SimpleITKPINVOKE.BinaryErodeImageFilter_Execute(swigCPtr, Image.getCPtr(image1)), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
