//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace itk.simple {

public class CannySegmentationLevelSetImageFilter : ImageFilter {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal CannySegmentationLevelSetImageFilter(global::System.IntPtr cPtr, bool cMemoryOwn) : base(SimpleITKPINVOKE.CannySegmentationLevelSetImageFilter_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CannySegmentationLevelSetImageFilter obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CannySegmentationLevelSetImageFilter obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SimpleITKPINVOKE.delete_CannySegmentationLevelSetImageFilter(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public CannySegmentationLevelSetImageFilter() : this(SimpleITKPINVOKE.new_CannySegmentationLevelSetImageFilter(), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetThreshold(double Threshold) {
    SimpleITKPINVOKE.CannySegmentationLevelSetImageFilter_SetThreshold(swigCPtr, Threshold);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetThreshold() {
    double ret = SimpleITKPINVOKE.CannySegmentationLevelSetImageFilter_GetThreshold(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetVariance(double Variance) {
    SimpleITKPINVOKE.CannySegmentationLevelSetImageFilter_SetVariance(swigCPtr, Variance);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetVariance() {
    double ret = SimpleITKPINVOKE.CannySegmentationLevelSetImageFilter_GetVariance(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetMaximumRMSError(double MaximumRMSError) {
    SimpleITKPINVOKE.CannySegmentationLevelSetImageFilter_SetMaximumRMSError(swigCPtr, MaximumRMSError);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetMaximumRMSError() {
    double ret = SimpleITKPINVOKE.CannySegmentationLevelSetImageFilter_GetMaximumRMSError(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetPropagationScaling(double PropagationScaling) {
    SimpleITKPINVOKE.CannySegmentationLevelSetImageFilter_SetPropagationScaling(swigCPtr, PropagationScaling);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetPropagationScaling() {
    double ret = SimpleITKPINVOKE.CannySegmentationLevelSetImageFilter_GetPropagationScaling(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetCurvatureScaling(double CurvatureScaling) {
    SimpleITKPINVOKE.CannySegmentationLevelSetImageFilter_SetCurvatureScaling(swigCPtr, CurvatureScaling);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetCurvatureScaling() {
    double ret = SimpleITKPINVOKE.CannySegmentationLevelSetImageFilter_GetCurvatureScaling(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetAdvectionScaling(double AdvectionScaling) {
    SimpleITKPINVOKE.CannySegmentationLevelSetImageFilter_SetAdvectionScaling(swigCPtr, AdvectionScaling);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetAdvectionScaling() {
    double ret = SimpleITKPINVOKE.CannySegmentationLevelSetImageFilter_GetAdvectionScaling(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetNumberOfIterations(uint NumberOfIterations) {
    SimpleITKPINVOKE.CannySegmentationLevelSetImageFilter_SetNumberOfIterations(swigCPtr, NumberOfIterations);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint GetNumberOfIterations() {
    uint ret = SimpleITKPINVOKE.CannySegmentationLevelSetImageFilter_GetNumberOfIterations(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetReverseExpansionDirection(bool ReverseExpansionDirection) {
    SimpleITKPINVOKE.CannySegmentationLevelSetImageFilter_SetReverseExpansionDirection(swigCPtr, ReverseExpansionDirection);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void ReverseExpansionDirectionOn() {
    SimpleITKPINVOKE.CannySegmentationLevelSetImageFilter_ReverseExpansionDirectionOn(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void ReverseExpansionDirectionOff() {
    SimpleITKPINVOKE.CannySegmentationLevelSetImageFilter_ReverseExpansionDirectionOff(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool GetReverseExpansionDirection() {
    bool ret = SimpleITKPINVOKE.CannySegmentationLevelSetImageFilter_GetReverseExpansionDirection(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetIsoSurfaceValue(double IsoSurfaceValue) {
    SimpleITKPINVOKE.CannySegmentationLevelSetImageFilter_SetIsoSurfaceValue(swigCPtr, IsoSurfaceValue);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetIsoSurfaceValue() {
    double ret = SimpleITKPINVOKE.CannySegmentationLevelSetImageFilter_GetIsoSurfaceValue(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public uint GetElapsedIterations() {
    uint ret = SimpleITKPINVOKE.CannySegmentationLevelSetImageFilter_GetElapsedIterations(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetRMSChange() {
    double ret = SimpleITKPINVOKE.CannySegmentationLevelSetImageFilter_GetRMSChange(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Image GetCannyImage() {
    Image ret = new Image(SimpleITKPINVOKE.CannySegmentationLevelSetImageFilter_GetCannyImage(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string GetName() {
    string ret = SimpleITKPINVOKE.CannySegmentationLevelSetImageFilter_GetName(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string ToString() {
    string ret = SimpleITKPINVOKE.CannySegmentationLevelSetImageFilter_ToString(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Image Execute(Image initialImage, Image featureImage) {
    Image ret = new Image(SimpleITKPINVOKE.CannySegmentationLevelSetImageFilter_Execute(swigCPtr, Image.getCPtr(initialImage), Image.getCPtr(featureImage)), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
