//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace itk.simple {

public class CollidingFrontsImageFilter : ImageFilter {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal CollidingFrontsImageFilter(global::System.IntPtr cPtr, bool cMemoryOwn) : base(SimpleITKPINVOKE.CollidingFrontsImageFilter_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CollidingFrontsImageFilter obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CollidingFrontsImageFilter obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SimpleITKPINVOKE.delete_CollidingFrontsImageFilter(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public CollidingFrontsImageFilter() : this(SimpleITKPINVOKE.new_CollidingFrontsImageFilter(), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetSeedPoints1(VectorUIntList SeedPoints1) {
    SimpleITKPINVOKE.CollidingFrontsImageFilter_SetSeedPoints1(swigCPtr, VectorUIntList.getCPtr(SeedPoints1));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorUIntList GetSeedPoints1() {
    VectorUIntList ret = new VectorUIntList(SimpleITKPINVOKE.CollidingFrontsImageFilter_GetSeedPoints1(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void AddSeedPoint1(VectorUInt32 point) {
    SimpleITKPINVOKE.CollidingFrontsImageFilter_AddSeedPoint1(swigCPtr, VectorUInt32.getCPtr(point));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void ClearSeedPoints1() {
    SimpleITKPINVOKE.CollidingFrontsImageFilter_ClearSeedPoints1(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetSeedPoints2(VectorUIntList SeedPoints2) {
    SimpleITKPINVOKE.CollidingFrontsImageFilter_SetSeedPoints2(swigCPtr, VectorUIntList.getCPtr(SeedPoints2));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorUIntList GetSeedPoints2() {
    VectorUIntList ret = new VectorUIntList(SimpleITKPINVOKE.CollidingFrontsImageFilter_GetSeedPoints2(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void AddSeedPoint2(VectorUInt32 point) {
    SimpleITKPINVOKE.CollidingFrontsImageFilter_AddSeedPoint2(swigCPtr, VectorUInt32.getCPtr(point));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void ClearSeedPoints2() {
    SimpleITKPINVOKE.CollidingFrontsImageFilter_ClearSeedPoints2(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetApplyConnectivity(bool ApplyConnectivity) {
    SimpleITKPINVOKE.CollidingFrontsImageFilter_SetApplyConnectivity(swigCPtr, ApplyConnectivity);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void ApplyConnectivityOn() {
    SimpleITKPINVOKE.CollidingFrontsImageFilter_ApplyConnectivityOn(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void ApplyConnectivityOff() {
    SimpleITKPINVOKE.CollidingFrontsImageFilter_ApplyConnectivityOff(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool GetApplyConnectivity() {
    bool ret = SimpleITKPINVOKE.CollidingFrontsImageFilter_GetApplyConnectivity(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetNegativeEpsilon(double NegativeEpsilon) {
    SimpleITKPINVOKE.CollidingFrontsImageFilter_SetNegativeEpsilon(swigCPtr, NegativeEpsilon);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetNegativeEpsilon() {
    double ret = SimpleITKPINVOKE.CollidingFrontsImageFilter_GetNegativeEpsilon(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetStopOnTargets(bool StopOnTargets) {
    SimpleITKPINVOKE.CollidingFrontsImageFilter_SetStopOnTargets(swigCPtr, StopOnTargets);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void StopOnTargetsOn() {
    SimpleITKPINVOKE.CollidingFrontsImageFilter_StopOnTargetsOn(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void StopOnTargetsOff() {
    SimpleITKPINVOKE.CollidingFrontsImageFilter_StopOnTargetsOff(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool GetStopOnTargets() {
    bool ret = SimpleITKPINVOKE.CollidingFrontsImageFilter_GetStopOnTargets(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string GetName() {
    string ret = SimpleITKPINVOKE.CollidingFrontsImageFilter_GetName(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string ToString() {
    string ret = SimpleITKPINVOKE.CollidingFrontsImageFilter_ToString(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Image Execute(Image image1) {
    Image ret = new Image(SimpleITKPINVOKE.CollidingFrontsImageFilter_Execute(swigCPtr, Image.getCPtr(image1)), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
