//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace itk.simple {

public class Command : ObjectOwnedBase {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal Command(global::System.IntPtr cPtr, bool cMemoryOwn) : base(SimpleITKPINVOKE.Command_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Command obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Command obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SimpleITKPINVOKE.delete_Command(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public Command() : this(SimpleITKPINVOKE.new_Command(), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    SwigDirectorConnect();
  }

  public override string GetName() {
    string ret = (SwigDerivedClassHasMethod("GetName", swigMethodTypes0) ? SimpleITKPINVOKE.Command_GetNameSwigExplicitCommand(swigCPtr) : SimpleITKPINVOKE.Command_GetName(swigCPtr));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void SetName(string n) {
    if (SwigDerivedClassHasMethod("SetName", swigMethodTypes1)) SimpleITKPINVOKE.Command_SetNameSwigExplicitCommand(swigCPtr, n); else SimpleITKPINVOKE.Command_SetName(swigCPtr, n);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void Execute() {
    if (SwigDerivedClassHasMethod("Execute", swigMethodTypes2)) SimpleITKPINVOKE.Command_ExecuteSwigExplicitCommand(swigCPtr); else SimpleITKPINVOKE.Command_Execute(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("GetName", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateCommand_0(SwigDirectorMethodGetName);
    if (SwigDerivedClassHasMethod("SetName", swigMethodTypes1))
      swigDelegate1 = new SwigDelegateCommand_1(SwigDirectorMethodSetName);
    if (SwigDerivedClassHasMethod("Execute", swigMethodTypes2))
      swigDelegate2 = new SwigDelegateCommand_2(SwigDirectorMethodExecute);
    SimpleITKPINVOKE.Command_director_connect(swigCPtr, swigDelegate0, swigDelegate1, swigDelegate2);
  }

  private bool SwigDerivedClassHasMethod(string methodName, global::System.Type[] methodTypes) {
    global::System.Reflection.MethodInfo[] methodInfos = this.GetType().GetMethods(
        global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance);
    foreach (global::System.Reflection.MethodInfo methodInfo in methodInfos) {
      if (methodInfo.DeclaringType == null)
        continue;

      if (methodInfo.Name != methodName)
        continue;

      var parameters = methodInfo.GetParameters();
      if (parameters.Length != methodTypes.Length)
        continue;

      bool parametersMatch = true;
      for (var i = 0; i < parameters.Length; i++) {
        if (parameters[i].ParameterType != methodTypes[i]) {
          parametersMatch = false;
          break;
        }
      }

      if (!parametersMatch)
        continue;

      if (methodInfo.IsVirtual && (methodInfo.DeclaringType.IsSubclassOf(typeof(Command))) &&
        methodInfo.DeclaringType != methodInfo.GetBaseDefinition().DeclaringType) {
        return true;
      }
    }

    return false;
  }

  private string SwigDirectorMethodGetName() {
    return GetName();
  }

  private void SwigDirectorMethodSetName(string n) {
    SetName(n);
  }

  private void SwigDirectorMethodExecute() {
    Execute();
  }

  public delegate string SwigDelegateCommand_0();
  public delegate void SwigDelegateCommand_1(string n);
  public delegate void SwigDelegateCommand_2();

  private SwigDelegateCommand_0 swigDelegate0;
  private SwigDelegateCommand_1 swigDelegate1;
  private SwigDelegateCommand_2 swigDelegate2;

  private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] {  };
  private static global::System.Type[] swigMethodTypes1 = new global::System.Type[] { typeof(string) };
  private static global::System.Type[] swigMethodTypes2 = new global::System.Type[] {  };
}

}
