//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace itk.simple {

public class CurvatureAnisotropicDiffusionImageFilter : ImageFilter {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal CurvatureAnisotropicDiffusionImageFilter(global::System.IntPtr cPtr, bool cMemoryOwn) : base(SimpleITKPINVOKE.CurvatureAnisotropicDiffusionImageFilter_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CurvatureAnisotropicDiffusionImageFilter obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CurvatureAnisotropicDiffusionImageFilter obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SimpleITKPINVOKE.delete_CurvatureAnisotropicDiffusionImageFilter(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public CurvatureAnisotropicDiffusionImageFilter() : this(SimpleITKPINVOKE.new_CurvatureAnisotropicDiffusionImageFilter(), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetTimeStep(double TimeStep) {
    SimpleITKPINVOKE.CurvatureAnisotropicDiffusionImageFilter_SetTimeStep(swigCPtr, TimeStep);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetTimeStep() {
    double ret = SimpleITKPINVOKE.CurvatureAnisotropicDiffusionImageFilter_GetTimeStep(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetConductanceParameter(double ConductanceParameter) {
    SimpleITKPINVOKE.CurvatureAnisotropicDiffusionImageFilter_SetConductanceParameter(swigCPtr, ConductanceParameter);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetConductanceParameter() {
    double ret = SimpleITKPINVOKE.CurvatureAnisotropicDiffusionImageFilter_GetConductanceParameter(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetConductanceScalingUpdateInterval(uint ConductanceScalingUpdateInterval) {
    SimpleITKPINVOKE.CurvatureAnisotropicDiffusionImageFilter_SetConductanceScalingUpdateInterval(swigCPtr, ConductanceScalingUpdateInterval);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint GetConductanceScalingUpdateInterval() {
    uint ret = SimpleITKPINVOKE.CurvatureAnisotropicDiffusionImageFilter_GetConductanceScalingUpdateInterval(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetNumberOfIterations(uint NumberOfIterations) {
    SimpleITKPINVOKE.CurvatureAnisotropicDiffusionImageFilter_SetNumberOfIterations(swigCPtr, NumberOfIterations);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint GetNumberOfIterations() {
    uint ret = SimpleITKPINVOKE.CurvatureAnisotropicDiffusionImageFilter_GetNumberOfIterations(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string GetName() {
    string ret = SimpleITKPINVOKE.CurvatureAnisotropicDiffusionImageFilter_GetName(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string ToString() {
    string ret = SimpleITKPINVOKE.CurvatureAnisotropicDiffusionImageFilter_ToString(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Image Execute(Image image1) {
    Image ret = new Image(SimpleITKPINVOKE.CurvatureAnisotropicDiffusionImageFilter_Execute(swigCPtr, Image.getCPtr(image1)), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double EstimateOptimalTimeStep(Image inImage) {
    double ret = SimpleITKPINVOKE.CurvatureAnisotropicDiffusionImageFilter_EstimateOptimalTimeStep(swigCPtr, Image.getCPtr(inImage));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
