//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace itk.simple {

public class DemonsRegistrationFilter : ImageFilter {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal DemonsRegistrationFilter(global::System.IntPtr cPtr, bool cMemoryOwn) : base(SimpleITKPINVOKE.DemonsRegistrationFilter_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DemonsRegistrationFilter obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(DemonsRegistrationFilter obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SimpleITKPINVOKE.delete_DemonsRegistrationFilter(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public DemonsRegistrationFilter() : this(SimpleITKPINVOKE.new_DemonsRegistrationFilter(), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetStandardDeviations(VectorDouble StandardDeviations) {
    SimpleITKPINVOKE.DemonsRegistrationFilter_SetStandardDeviations__SWIG_0(swigCPtr, VectorDouble.getCPtr(StandardDeviations));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetStandardDeviations(double value) {
    SimpleITKPINVOKE.DemonsRegistrationFilter_SetStandardDeviations__SWIG_1(swigCPtr, value);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorDouble GetStandardDeviations() {
    VectorDouble ret = new VectorDouble(SimpleITKPINVOKE.DemonsRegistrationFilter_GetStandardDeviations(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetNumberOfIterations(uint NumberOfIterations) {
    SimpleITKPINVOKE.DemonsRegistrationFilter_SetNumberOfIterations(swigCPtr, NumberOfIterations);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint GetNumberOfIterations() {
    uint ret = SimpleITKPINVOKE.DemonsRegistrationFilter_GetNumberOfIterations(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetMaximumRMSError(double MaximumRMSError) {
    SimpleITKPINVOKE.DemonsRegistrationFilter_SetMaximumRMSError(swigCPtr, MaximumRMSError);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetMaximumRMSError() {
    double ret = SimpleITKPINVOKE.DemonsRegistrationFilter_GetMaximumRMSError(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetUseMovingImageGradient(bool UseMovingImageGradient) {
    SimpleITKPINVOKE.DemonsRegistrationFilter_SetUseMovingImageGradient(swigCPtr, UseMovingImageGradient);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void UseMovingImageGradientOn() {
    SimpleITKPINVOKE.DemonsRegistrationFilter_UseMovingImageGradientOn(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void UseMovingImageGradientOff() {
    SimpleITKPINVOKE.DemonsRegistrationFilter_UseMovingImageGradientOff(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool GetUseMovingImageGradient() {
    bool ret = SimpleITKPINVOKE.DemonsRegistrationFilter_GetUseMovingImageGradient(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetSmoothDisplacementField(bool SmoothDisplacementField) {
    SimpleITKPINVOKE.DemonsRegistrationFilter_SetSmoothDisplacementField(swigCPtr, SmoothDisplacementField);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SmoothDisplacementFieldOn() {
    SimpleITKPINVOKE.DemonsRegistrationFilter_SmoothDisplacementFieldOn(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SmoothDisplacementFieldOff() {
    SimpleITKPINVOKE.DemonsRegistrationFilter_SmoothDisplacementFieldOff(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool GetSmoothDisplacementField() {
    bool ret = SimpleITKPINVOKE.DemonsRegistrationFilter_GetSmoothDisplacementField(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetSmoothUpdateField(bool SmoothUpdateField) {
    SimpleITKPINVOKE.DemonsRegistrationFilter_SetSmoothUpdateField(swigCPtr, SmoothUpdateField);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SmoothUpdateFieldOn() {
    SimpleITKPINVOKE.DemonsRegistrationFilter_SmoothUpdateFieldOn(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SmoothUpdateFieldOff() {
    SimpleITKPINVOKE.DemonsRegistrationFilter_SmoothUpdateFieldOff(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool GetSmoothUpdateField() {
    bool ret = SimpleITKPINVOKE.DemonsRegistrationFilter_GetSmoothUpdateField(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetUpdateFieldStandardDeviations(VectorDouble UpdateFieldStandardDeviations) {
    SimpleITKPINVOKE.DemonsRegistrationFilter_SetUpdateFieldStandardDeviations__SWIG_0(swigCPtr, VectorDouble.getCPtr(UpdateFieldStandardDeviations));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetUpdateFieldStandardDeviations(double value) {
    SimpleITKPINVOKE.DemonsRegistrationFilter_SetUpdateFieldStandardDeviations__SWIG_1(swigCPtr, value);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorDouble GetUpdateFieldStandardDeviations() {
    VectorDouble ret = new VectorDouble(SimpleITKPINVOKE.DemonsRegistrationFilter_GetUpdateFieldStandardDeviations(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetMaximumKernelWidth(uint MaximumKernelWidth) {
    SimpleITKPINVOKE.DemonsRegistrationFilter_SetMaximumKernelWidth(swigCPtr, MaximumKernelWidth);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint GetMaximumKernelWidth() {
    uint ret = SimpleITKPINVOKE.DemonsRegistrationFilter_GetMaximumKernelWidth(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetMaximumError(double MaximumError) {
    SimpleITKPINVOKE.DemonsRegistrationFilter_SetMaximumError(swigCPtr, MaximumError);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetMaximumError() {
    double ret = SimpleITKPINVOKE.DemonsRegistrationFilter_GetMaximumError(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetIntensityDifferenceThreshold(double IntensityDifferenceThreshold) {
    SimpleITKPINVOKE.DemonsRegistrationFilter_SetIntensityDifferenceThreshold(swigCPtr, IntensityDifferenceThreshold);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetIntensityDifferenceThreshold() {
    double ret = SimpleITKPINVOKE.DemonsRegistrationFilter_GetIntensityDifferenceThreshold(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetUseImageSpacing(bool UseImageSpacing) {
    SimpleITKPINVOKE.DemonsRegistrationFilter_SetUseImageSpacing(swigCPtr, UseImageSpacing);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void UseImageSpacingOn() {
    SimpleITKPINVOKE.DemonsRegistrationFilter_UseImageSpacingOn(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void UseImageSpacingOff() {
    SimpleITKPINVOKE.DemonsRegistrationFilter_UseImageSpacingOff(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool GetUseImageSpacing() {
    bool ret = SimpleITKPINVOKE.DemonsRegistrationFilter_GetUseImageSpacing(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public uint GetElapsedIterations() {
    uint ret = SimpleITKPINVOKE.DemonsRegistrationFilter_GetElapsedIterations(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetRMSChange() {
    double ret = SimpleITKPINVOKE.DemonsRegistrationFilter_GetRMSChange(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetMetric() {
    double ret = SimpleITKPINVOKE.DemonsRegistrationFilter_GetMetric(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void StopRegistration() {
    SimpleITKPINVOKE.DemonsRegistrationFilter_StopRegistration(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public override string GetName() {
    string ret = SimpleITKPINVOKE.DemonsRegistrationFilter_GetName(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string ToString() {
    string ret = SimpleITKPINVOKE.DemonsRegistrationFilter_ToString(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Image Execute(Image fixedImage, Image movingImage, Image initialDisplacementField) {
    Image ret = new Image(SimpleITKPINVOKE.DemonsRegistrationFilter_Execute__SWIG_0(swigCPtr, Image.getCPtr(fixedImage), Image.getCPtr(movingImage), Image.getCPtr(initialDisplacementField)), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Image Execute(Image fixedImage, Image movingImage) {
    Image ret = new Image(SimpleITKPINVOKE.DemonsRegistrationFilter_Execute__SWIG_1(swigCPtr, Image.getCPtr(fixedImage), Image.getCPtr(movingImage)), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
