//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace itk.simple {

public class DiffeomorphicDemonsRegistrationFilter : ImageFilter {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal DiffeomorphicDemonsRegistrationFilter(global::System.IntPtr cPtr, bool cMemoryOwn) : base(SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DiffeomorphicDemonsRegistrationFilter obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(DiffeomorphicDemonsRegistrationFilter obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SimpleITKPINVOKE.delete_DiffeomorphicDemonsRegistrationFilter(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public DiffeomorphicDemonsRegistrationFilter() : this(SimpleITKPINVOKE.new_DiffeomorphicDemonsRegistrationFilter(), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetStandardDeviations(VectorDouble StandardDeviations) {
    SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_SetStandardDeviations__SWIG_0(swigCPtr, VectorDouble.getCPtr(StandardDeviations));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetStandardDeviations(double value) {
    SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_SetStandardDeviations__SWIG_1(swigCPtr, value);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorDouble GetStandardDeviations() {
    VectorDouble ret = new VectorDouble(SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_GetStandardDeviations(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetNumberOfIterations(uint NumberOfIterations) {
    SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_SetNumberOfIterations(swigCPtr, NumberOfIterations);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint GetNumberOfIterations() {
    uint ret = SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_GetNumberOfIterations(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetMaximumRMSError(double MaximumRMSError) {
    SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_SetMaximumRMSError(swigCPtr, MaximumRMSError);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetMaximumRMSError() {
    double ret = SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_GetMaximumRMSError(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetUseGradientType(DiffeomorphicDemonsRegistrationFilter.UseGradientTypeType UseGradientType) {
    SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_SetUseGradientType(swigCPtr, UseGradientType.swigValue);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public DiffeomorphicDemonsRegistrationFilter.UseGradientTypeType GetUseGradientType() {
    DiffeomorphicDemonsRegistrationFilter.UseGradientTypeType ret = DiffeomorphicDemonsRegistrationFilter.UseGradientTypeType.swigToEnum(SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_GetUseGradientType(swigCPtr));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetUseFirstOrderExp(bool UseFirstOrderExp) {
    SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_SetUseFirstOrderExp(swigCPtr, UseFirstOrderExp);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void UseFirstOrderExpOn() {
    SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_UseFirstOrderExpOn(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void UseFirstOrderExpOff() {
    SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_UseFirstOrderExpOff(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool GetUseFirstOrderExp() {
    bool ret = SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_GetUseFirstOrderExp(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetMaximumUpdateStepLength(double MaximumUpdateStepLength) {
    SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_SetMaximumUpdateStepLength(swigCPtr, MaximumUpdateStepLength);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetMaximumUpdateStepLength() {
    double ret = SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_GetMaximumUpdateStepLength(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetSmoothDisplacementField(bool SmoothDisplacementField) {
    SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_SetSmoothDisplacementField(swigCPtr, SmoothDisplacementField);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SmoothDisplacementFieldOn() {
    SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_SmoothDisplacementFieldOn(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SmoothDisplacementFieldOff() {
    SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_SmoothDisplacementFieldOff(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool GetSmoothDisplacementField() {
    bool ret = SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_GetSmoothDisplacementField(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetSmoothUpdateField(bool SmoothUpdateField) {
    SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_SetSmoothUpdateField(swigCPtr, SmoothUpdateField);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SmoothUpdateFieldOn() {
    SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_SmoothUpdateFieldOn(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SmoothUpdateFieldOff() {
    SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_SmoothUpdateFieldOff(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool GetSmoothUpdateField() {
    bool ret = SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_GetSmoothUpdateField(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetUpdateFieldStandardDeviations(VectorDouble UpdateFieldStandardDeviations) {
    SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_SetUpdateFieldStandardDeviations__SWIG_0(swigCPtr, VectorDouble.getCPtr(UpdateFieldStandardDeviations));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetUpdateFieldStandardDeviations(double value) {
    SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_SetUpdateFieldStandardDeviations__SWIG_1(swigCPtr, value);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorDouble GetUpdateFieldStandardDeviations() {
    VectorDouble ret = new VectorDouble(SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_GetUpdateFieldStandardDeviations(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetMaximumKernelWidth(uint MaximumKernelWidth) {
    SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_SetMaximumKernelWidth(swigCPtr, MaximumKernelWidth);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint GetMaximumKernelWidth() {
    uint ret = SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_GetMaximumKernelWidth(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetMaximumError(double MaximumError) {
    SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_SetMaximumError(swigCPtr, MaximumError);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetMaximumError() {
    double ret = SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_GetMaximumError(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetIntensityDifferenceThreshold(double IntensityDifferenceThreshold) {
    SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_SetIntensityDifferenceThreshold(swigCPtr, IntensityDifferenceThreshold);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetIntensityDifferenceThreshold() {
    double ret = SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_GetIntensityDifferenceThreshold(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetUseImageSpacing(bool UseImageSpacing) {
    SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_SetUseImageSpacing(swigCPtr, UseImageSpacing);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void UseImageSpacingOn() {
    SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_UseImageSpacingOn(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void UseImageSpacingOff() {
    SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_UseImageSpacingOff(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool GetUseImageSpacing() {
    bool ret = SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_GetUseImageSpacing(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public uint GetElapsedIterations() {
    uint ret = SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_GetElapsedIterations(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetRMSChange() {
    double ret = SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_GetRMSChange(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetMetric() {
    double ret = SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_GetMetric(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void StopRegistration() {
    SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_StopRegistration(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public override string GetName() {
    string ret = SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_GetName(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string ToString() {
    string ret = SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_ToString(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Image Execute(Image fixedImage, Image movingImage, Image initialDisplacementField) {
    Image ret = new Image(SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_Execute__SWIG_0(swigCPtr, Image.getCPtr(fixedImage), Image.getCPtr(movingImage), Image.getCPtr(initialDisplacementField)), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Image Execute(Image fixedImage, Image movingImage) {
    Image ret = new Image(SimpleITKPINVOKE.DiffeomorphicDemonsRegistrationFilter_Execute__SWIG_1(swigCPtr, Image.getCPtr(fixedImage), Image.getCPtr(movingImage)), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public sealed class UseGradientTypeType {
    public static readonly DiffeomorphicDemonsRegistrationFilter.UseGradientTypeType Symmetric = new DiffeomorphicDemonsRegistrationFilter.UseGradientTypeType("Symmetric");
    public static readonly DiffeomorphicDemonsRegistrationFilter.UseGradientTypeType Fixed = new DiffeomorphicDemonsRegistrationFilter.UseGradientTypeType("Fixed");
    public static readonly DiffeomorphicDemonsRegistrationFilter.UseGradientTypeType WarpedMoving = new DiffeomorphicDemonsRegistrationFilter.UseGradientTypeType("WarpedMoving");
    public static readonly DiffeomorphicDemonsRegistrationFilter.UseGradientTypeType MappedMoving = new DiffeomorphicDemonsRegistrationFilter.UseGradientTypeType("MappedMoving");

    public readonly int swigValue;

    public static UseGradientTypeType swigToEnum(int swigValue) {
      if (swigValue < swigValues.Length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.Length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new global::System.ArgumentOutOfRangeException("No enum UseGradientTypeType with value " + swigValue);
    }

    public override string ToString() {
      return swigName;
    }

    private UseGradientTypeType(string swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private UseGradientTypeType(string swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private UseGradientTypeType(string swigName, UseGradientTypeType swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static UseGradientTypeType[] swigValues = { Symmetric, Fixed, WarpedMoving, MappedMoving };
    private static int swigNext = 0;
    private readonly string swigName;
  }

}

}
