//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace itk.simple {

public class DiscreteGaussianDerivativeImageFilter : ImageFilter {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal DiscreteGaussianDerivativeImageFilter(global::System.IntPtr cPtr, bool cMemoryOwn) : base(SimpleITKPINVOKE.DiscreteGaussianDerivativeImageFilter_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DiscreteGaussianDerivativeImageFilter obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(DiscreteGaussianDerivativeImageFilter obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SimpleITKPINVOKE.delete_DiscreteGaussianDerivativeImageFilter(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public DiscreteGaussianDerivativeImageFilter() : this(SimpleITKPINVOKE.new_DiscreteGaussianDerivativeImageFilter(), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetVariance(VectorDouble Variance) {
    SimpleITKPINVOKE.DiscreteGaussianDerivativeImageFilter_SetVariance__SWIG_0(swigCPtr, VectorDouble.getCPtr(Variance));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetVariance(double value) {
    SimpleITKPINVOKE.DiscreteGaussianDerivativeImageFilter_SetVariance__SWIG_1(swigCPtr, value);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorDouble GetVariance() {
    VectorDouble ret = new VectorDouble(SimpleITKPINVOKE.DiscreteGaussianDerivativeImageFilter_GetVariance(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetOrder(VectorUInt32 Order) {
    SimpleITKPINVOKE.DiscreteGaussianDerivativeImageFilter_SetOrder__SWIG_0(swigCPtr, VectorUInt32.getCPtr(Order));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetOrder(uint value) {
    SimpleITKPINVOKE.DiscreteGaussianDerivativeImageFilter_SetOrder__SWIG_1(swigCPtr, value);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorUInt32 GetOrder() {
    VectorUInt32 ret = new VectorUInt32(SimpleITKPINVOKE.DiscreteGaussianDerivativeImageFilter_GetOrder(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetMaximumKernelWidth(uint MaximumKernelWidth) {
    SimpleITKPINVOKE.DiscreteGaussianDerivativeImageFilter_SetMaximumKernelWidth(swigCPtr, MaximumKernelWidth);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint GetMaximumKernelWidth() {
    uint ret = SimpleITKPINVOKE.DiscreteGaussianDerivativeImageFilter_GetMaximumKernelWidth(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetMaximumError(double MaximumError) {
    SimpleITKPINVOKE.DiscreteGaussianDerivativeImageFilter_SetMaximumError(swigCPtr, MaximumError);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetMaximumError() {
    double ret = SimpleITKPINVOKE.DiscreteGaussianDerivativeImageFilter_GetMaximumError(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetUseImageSpacing(bool UseImageSpacing) {
    SimpleITKPINVOKE.DiscreteGaussianDerivativeImageFilter_SetUseImageSpacing(swigCPtr, UseImageSpacing);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void UseImageSpacingOn() {
    SimpleITKPINVOKE.DiscreteGaussianDerivativeImageFilter_UseImageSpacingOn(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void UseImageSpacingOff() {
    SimpleITKPINVOKE.DiscreteGaussianDerivativeImageFilter_UseImageSpacingOff(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool GetUseImageSpacing() {
    bool ret = SimpleITKPINVOKE.DiscreteGaussianDerivativeImageFilter_GetUseImageSpacing(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetNormalizeAcrossScale(bool NormalizeAcrossScale) {
    SimpleITKPINVOKE.DiscreteGaussianDerivativeImageFilter_SetNormalizeAcrossScale(swigCPtr, NormalizeAcrossScale);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void NormalizeAcrossScaleOn() {
    SimpleITKPINVOKE.DiscreteGaussianDerivativeImageFilter_NormalizeAcrossScaleOn(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void NormalizeAcrossScaleOff() {
    SimpleITKPINVOKE.DiscreteGaussianDerivativeImageFilter_NormalizeAcrossScaleOff(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool GetNormalizeAcrossScale() {
    bool ret = SimpleITKPINVOKE.DiscreteGaussianDerivativeImageFilter_GetNormalizeAcrossScale(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string GetName() {
    string ret = SimpleITKPINVOKE.DiscreteGaussianDerivativeImageFilter_GetName(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string ToString() {
    string ret = SimpleITKPINVOKE.DiscreteGaussianDerivativeImageFilter_ToString(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Image Execute(Image image1) {
    Image ret = new Image(SimpleITKPINVOKE.DiscreteGaussianDerivativeImageFilter_Execute(swigCPtr, Image.getCPtr(image1)), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
