//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace itk.simple {

public class DisplacementFieldTransform : Transform {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal DisplacementFieldTransform(global::System.IntPtr cPtr, bool cMemoryOwn) : base(SimpleITKPINVOKE.DisplacementFieldTransform_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DisplacementFieldTransform obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(DisplacementFieldTransform obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SimpleITKPINVOKE.delete_DisplacementFieldTransform(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public DisplacementFieldTransform(uint dimensions) : this(SimpleITKPINVOKE.new_DisplacementFieldTransform__SWIG_0(dimensions), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public DisplacementFieldTransform(Image arg0) : this(SimpleITKPINVOKE.new_DisplacementFieldTransform__SWIG_1(Image.getCPtr(arg0)), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public DisplacementFieldTransform(DisplacementFieldTransform arg0) : this(SimpleITKPINVOKE.new_DisplacementFieldTransform__SWIG_2(DisplacementFieldTransform.getCPtr(arg0)), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public DisplacementFieldTransform(Transform arg0) : this(SimpleITKPINVOKE.new_DisplacementFieldTransform__SWIG_3(Transform.getCPtr(arg0)), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public override string GetName() {
    string ret = SimpleITKPINVOKE.DisplacementFieldTransform_GetName(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetDisplacementField(Image arg0) {
    SimpleITKPINVOKE.DisplacementFieldTransform_SetDisplacementField(swigCPtr, Image.getCPtr(arg0));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public Image GetDisplacementField() {
    Image ret = new Image(SimpleITKPINVOKE.DisplacementFieldTransform_GetDisplacementField(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetInverseDisplacementField(Image arg0) {
    SimpleITKPINVOKE.DisplacementFieldTransform_SetInverseDisplacementField(swigCPtr, Image.getCPtr(arg0));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public Image GetInverseDisplacementField() {
    Image ret = new Image(SimpleITKPINVOKE.DisplacementFieldTransform_GetInverseDisplacementField(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetInterpolator(InterpolatorEnum interp) {
    SimpleITKPINVOKE.DisplacementFieldTransform_SetInterpolator(swigCPtr, interp.swigValue);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetSmoothingOff() {
    SimpleITKPINVOKE.DisplacementFieldTransform_SetSmoothingOff(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetSmoothingGaussianOnUpdate(double varianceForUpdateField, double varianceForTotalField) {
    SimpleITKPINVOKE.DisplacementFieldTransform_SetSmoothingGaussianOnUpdate__SWIG_0(swigCPtr, varianceForUpdateField, varianceForTotalField);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetSmoothingGaussianOnUpdate(double varianceForUpdateField) {
    SimpleITKPINVOKE.DisplacementFieldTransform_SetSmoothingGaussianOnUpdate__SWIG_1(swigCPtr, varianceForUpdateField);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetSmoothingGaussianOnUpdate() {
    SimpleITKPINVOKE.DisplacementFieldTransform_SetSmoothingGaussianOnUpdate__SWIG_2(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetSmoothingBSplineOnUpdate(VectorUInt32 numberOfControlPointsForUpdateField, VectorUInt32 numberOfControlPointsForTotalField, bool enforceStationaryBoundary, uint order) {
    SimpleITKPINVOKE.DisplacementFieldTransform_SetSmoothingBSplineOnUpdate__SWIG_0(swigCPtr, VectorUInt32.getCPtr(numberOfControlPointsForUpdateField), VectorUInt32.getCPtr(numberOfControlPointsForTotalField), enforceStationaryBoundary, order);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetSmoothingBSplineOnUpdate(VectorUInt32 numberOfControlPointsForUpdateField, VectorUInt32 numberOfControlPointsForTotalField, bool enforceStationaryBoundary) {
    SimpleITKPINVOKE.DisplacementFieldTransform_SetSmoothingBSplineOnUpdate__SWIG_1(swigCPtr, VectorUInt32.getCPtr(numberOfControlPointsForUpdateField), VectorUInt32.getCPtr(numberOfControlPointsForTotalField), enforceStationaryBoundary);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetSmoothingBSplineOnUpdate(VectorUInt32 numberOfControlPointsForUpdateField, VectorUInt32 numberOfControlPointsForTotalField) {
    SimpleITKPINVOKE.DisplacementFieldTransform_SetSmoothingBSplineOnUpdate__SWIG_2(swigCPtr, VectorUInt32.getCPtr(numberOfControlPointsForUpdateField), VectorUInt32.getCPtr(numberOfControlPointsForTotalField));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetSmoothingBSplineOnUpdate(VectorUInt32 numberOfControlPointsForUpdateField) {
    SimpleITKPINVOKE.DisplacementFieldTransform_SetSmoothingBSplineOnUpdate__SWIG_3(swigCPtr, VectorUInt32.getCPtr(numberOfControlPointsForUpdateField));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetSmoothingBSplineOnUpdate() {
    SimpleITKPINVOKE.DisplacementFieldTransform_SetSmoothingBSplineOnUpdate__SWIG_4(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
