//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace itk.simple {

public class EqualImageFilter : ImageFilter {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal EqualImageFilter(global::System.IntPtr cPtr, bool cMemoryOwn) : base(SimpleITKPINVOKE.EqualImageFilter_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(EqualImageFilter obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(EqualImageFilter obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SimpleITKPINVOKE.delete_EqualImageFilter(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public EqualImageFilter() : this(SimpleITKPINVOKE.new_EqualImageFilter(), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetBackgroundValue(byte BackgroundValue) {
    SimpleITKPINVOKE.EqualImageFilter_SetBackgroundValue(swigCPtr, BackgroundValue);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public byte GetBackgroundValue() {
    byte ret = SimpleITKPINVOKE.EqualImageFilter_GetBackgroundValue(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetForegroundValue(byte ForegroundValue) {
    SimpleITKPINVOKE.EqualImageFilter_SetForegroundValue(swigCPtr, ForegroundValue);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public byte GetForegroundValue() {
    byte ret = SimpleITKPINVOKE.EqualImageFilter_GetForegroundValue(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string GetName() {
    string ret = SimpleITKPINVOKE.EqualImageFilter_GetName(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string ToString() {
    string ret = SimpleITKPINVOKE.EqualImageFilter_ToString(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Image Execute(Image image1, Image image2) {
    Image ret = new Image(SimpleITKPINVOKE.EqualImageFilter_Execute__SWIG_0(swigCPtr, Image.getCPtr(image1), Image.getCPtr(image2)), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Image Execute(Image image1, double constant) {
    Image ret = new Image(SimpleITKPINVOKE.EqualImageFilter_Execute__SWIG_1(swigCPtr, Image.getCPtr(image1), constant), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Image Execute(double constant, Image image2) {
    Image ret = new Image(SimpleITKPINVOKE.EqualImageFilter_Execute__SWIG_2(swigCPtr, constant, Image.getCPtr(image2)), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Image Execute(Image image1, double constant, byte backgroundValue, byte foregroundValue) {
    Image ret = new Image(SimpleITKPINVOKE.EqualImageFilter_Execute__SWIG_3(swigCPtr, Image.getCPtr(image1), constant, backgroundValue, foregroundValue), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Image Execute(double constant, Image image2, byte backgroundValue, byte foregroundValue) {
    Image ret = new Image(SimpleITKPINVOKE.EqualImageFilter_Execute__SWIG_4(swigCPtr, constant, Image.getCPtr(image2), backgroundValue, foregroundValue), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
