//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace itk.simple {

public class Euler3DTransform : Transform {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal Euler3DTransform(global::System.IntPtr cPtr, bool cMemoryOwn) : base(SimpleITKPINVOKE.Euler3DTransform_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Euler3DTransform obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Euler3DTransform obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SimpleITKPINVOKE.delete_Euler3DTransform(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public Euler3DTransform() : this(SimpleITKPINVOKE.new_Euler3DTransform__SWIG_0(), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public Euler3DTransform(VectorDouble fixedCenter, double angleX, double angleY, double angleZ, VectorDouble translation) : this(SimpleITKPINVOKE.new_Euler3DTransform__SWIG_1(VectorDouble.getCPtr(fixedCenter), angleX, angleY, angleZ, VectorDouble.getCPtr(translation)), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public Euler3DTransform(VectorDouble fixedCenter, double angleX, double angleY, double angleZ) : this(SimpleITKPINVOKE.new_Euler3DTransform__SWIG_2(VectorDouble.getCPtr(fixedCenter), angleX, angleY, angleZ), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public Euler3DTransform(VectorDouble fixedCenter, double angleX, double angleY) : this(SimpleITKPINVOKE.new_Euler3DTransform__SWIG_3(VectorDouble.getCPtr(fixedCenter), angleX, angleY), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public Euler3DTransform(VectorDouble fixedCenter, double angleX) : this(SimpleITKPINVOKE.new_Euler3DTransform__SWIG_4(VectorDouble.getCPtr(fixedCenter), angleX), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public Euler3DTransform(VectorDouble fixedCenter) : this(SimpleITKPINVOKE.new_Euler3DTransform__SWIG_5(VectorDouble.getCPtr(fixedCenter)), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public Euler3DTransform(Euler3DTransform arg0) : this(SimpleITKPINVOKE.new_Euler3DTransform__SWIG_6(Euler3DTransform.getCPtr(arg0)), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public Euler3DTransform(Transform arg0) : this(SimpleITKPINVOKE.new_Euler3DTransform__SWIG_7(Transform.getCPtr(arg0)), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public override string GetName() {
    string ret = SimpleITKPINVOKE.Euler3DTransform_GetName(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetCenter(VectorDouble params_) {
    SimpleITKPINVOKE.Euler3DTransform_SetCenter(swigCPtr, VectorDouble.getCPtr(params_));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorDouble GetCenter() {
    VectorDouble ret = new VectorDouble(SimpleITKPINVOKE.Euler3DTransform_GetCenter(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetAngleX() {
    double ret = SimpleITKPINVOKE.Euler3DTransform_GetAngleX(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetAngleY() {
    double ret = SimpleITKPINVOKE.Euler3DTransform_GetAngleY(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetAngleZ() {
    double ret = SimpleITKPINVOKE.Euler3DTransform_GetAngleZ(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetRotation(double angleX, double angleY, double angleZ) {
    SimpleITKPINVOKE.Euler3DTransform_SetRotation(swigCPtr, angleX, angleY, angleZ);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorDouble GetTranslation() {
    VectorDouble ret = new VectorDouble(SimpleITKPINVOKE.Euler3DTransform_GetTranslation(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetTranslation(VectorDouble translation) {
    SimpleITKPINVOKE.Euler3DTransform_SetTranslation(swigCPtr, VectorDouble.getCPtr(translation));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetComputeZYX(bool _arg) {
    SimpleITKPINVOKE.Euler3DTransform_SetComputeZYX(swigCPtr, _arg);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool GetComputeZYX() {
    bool ret = SimpleITKPINVOKE.Euler3DTransform_GetComputeZYX(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void ComputeZYXOn() {
    SimpleITKPINVOKE.Euler3DTransform_ComputeZYXOn(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void ComputeZYXOff() {
    SimpleITKPINVOKE.Euler3DTransform_ComputeZYXOff(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorDouble GetMatrix() {
    VectorDouble ret = new VectorDouble(SimpleITKPINVOKE.Euler3DTransform_GetMatrix(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetMatrix(VectorDouble matrix, double tolerance) {
    SimpleITKPINVOKE.Euler3DTransform_SetMatrix__SWIG_0(swigCPtr, VectorDouble.getCPtr(matrix), tolerance);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetMatrix(VectorDouble matrix) {
    SimpleITKPINVOKE.Euler3DTransform_SetMatrix__SWIG_1(swigCPtr, VectorDouble.getCPtr(matrix));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
