//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace itk.simple {

public class FastMarchingUpwindGradientImageFilter : ImageFilter {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal FastMarchingUpwindGradientImageFilter(global::System.IntPtr cPtr, bool cMemoryOwn) : base(SimpleITKPINVOKE.FastMarchingUpwindGradientImageFilter_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FastMarchingUpwindGradientImageFilter obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(FastMarchingUpwindGradientImageFilter obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SimpleITKPINVOKE.delete_FastMarchingUpwindGradientImageFilter(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public FastMarchingUpwindGradientImageFilter() : this(SimpleITKPINVOKE.new_FastMarchingUpwindGradientImageFilter(), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetTrialPoints(VectorUIntList TrialPoints) {
    SimpleITKPINVOKE.FastMarchingUpwindGradientImageFilter_SetTrialPoints(swigCPtr, VectorUIntList.getCPtr(TrialPoints));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorUIntList GetTrialPoints() {
    VectorUIntList ret = new VectorUIntList(SimpleITKPINVOKE.FastMarchingUpwindGradientImageFilter_GetTrialPoints(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void AddTrialPoint(VectorUInt32 point) {
    SimpleITKPINVOKE.FastMarchingUpwindGradientImageFilter_AddTrialPoint(swigCPtr, VectorUInt32.getCPtr(point));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void ClearTrialPoints() {
    SimpleITKPINVOKE.FastMarchingUpwindGradientImageFilter_ClearTrialPoints(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetNumberOfTargets(uint NumberOfTargets) {
    SimpleITKPINVOKE.FastMarchingUpwindGradientImageFilter_SetNumberOfTargets(swigCPtr, NumberOfTargets);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint GetNumberOfTargets() {
    uint ret = SimpleITKPINVOKE.FastMarchingUpwindGradientImageFilter_GetNumberOfTargets(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetTargetPoints(VectorUIntList TargetPoints) {
    SimpleITKPINVOKE.FastMarchingUpwindGradientImageFilter_SetTargetPoints(swigCPtr, VectorUIntList.getCPtr(TargetPoints));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorUIntList GetTargetPoints() {
    VectorUIntList ret = new VectorUIntList(SimpleITKPINVOKE.FastMarchingUpwindGradientImageFilter_GetTargetPoints(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void AddTargetPoint(VectorUInt32 point) {
    SimpleITKPINVOKE.FastMarchingUpwindGradientImageFilter_AddTargetPoint(swigCPtr, VectorUInt32.getCPtr(point));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void ClearTargetPoints() {
    SimpleITKPINVOKE.FastMarchingUpwindGradientImageFilter_ClearTargetPoints(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetTargetOffset(double TargetOffset) {
    SimpleITKPINVOKE.FastMarchingUpwindGradientImageFilter_SetTargetOffset(swigCPtr, TargetOffset);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetTargetOffset() {
    double ret = SimpleITKPINVOKE.FastMarchingUpwindGradientImageFilter_GetTargetOffset(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetNormalizationFactor(double NormalizationFactor) {
    SimpleITKPINVOKE.FastMarchingUpwindGradientImageFilter_SetNormalizationFactor(swigCPtr, NormalizationFactor);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetNormalizationFactor() {
    double ret = SimpleITKPINVOKE.FastMarchingUpwindGradientImageFilter_GetNormalizationFactor(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetInitialTrialValues(VectorDouble InitialTrialValues) {
    SimpleITKPINVOKE.FastMarchingUpwindGradientImageFilter_SetInitialTrialValues(swigCPtr, VectorDouble.getCPtr(InitialTrialValues));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorDouble GetInitialTrialValues() {
    VectorDouble ret = new VectorDouble(SimpleITKPINVOKE.FastMarchingUpwindGradientImageFilter_GetInitialTrialValues(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Image GetGradientImage() {
    Image ret = new Image(SimpleITKPINVOKE.FastMarchingUpwindGradientImageFilter_GetGradientImage(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetTargetValue() {
    double ret = SimpleITKPINVOKE.FastMarchingUpwindGradientImageFilter_GetTargetValue(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string GetName() {
    string ret = SimpleITKPINVOKE.FastMarchingUpwindGradientImageFilter_GetName(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string ToString() {
    string ret = SimpleITKPINVOKE.FastMarchingUpwindGradientImageFilter_ToString(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Image Execute(Image image1) {
    Image ret = new Image(SimpleITKPINVOKE.FastMarchingUpwindGradientImageFilter_Execute(swigCPtr, Image.getCPtr(image1)), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
