//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace itk.simple {

public class ImageSeriesWriter : ProcessObject {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal ImageSeriesWriter(global::System.IntPtr cPtr, bool cMemoryOwn) : base(SimpleITKPINVOKE.ImageSeriesWriter_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ImageSeriesWriter obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ImageSeriesWriter obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SimpleITKPINVOKE.delete_ImageSeriesWriter(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public ImageSeriesWriter() : this(SimpleITKPINVOKE.new_ImageSeriesWriter(), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public override string ToString() {
    string ret = SimpleITKPINVOKE.ImageSeriesWriter_ToString(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual VectorString GetRegisteredImageIOs() {
    VectorString ret = new VectorString(SimpleITKPINVOKE.ImageSeriesWriter_GetRegisteredImageIOs(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void SetImageIO(string imageio) {
    SimpleITKPINVOKE.ImageSeriesWriter_SetImageIO(swigCPtr, imageio);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual string GetImageIO() {
    string ret = SimpleITKPINVOKE.ImageSeriesWriter_GetImageIO(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string GetName() {
    string ret = SimpleITKPINVOKE.ImageSeriesWriter_GetName(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetUseCompression(bool UseCompression) {
    SimpleITKPINVOKE.ImageSeriesWriter_SetUseCompression(swigCPtr, UseCompression);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool GetUseCompression() {
    bool ret = SimpleITKPINVOKE.ImageSeriesWriter_GetUseCompression(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void UseCompressionOn() {
    SimpleITKPINVOKE.ImageSeriesWriter_UseCompressionOn(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void UseCompressionOff() {
    SimpleITKPINVOKE.ImageSeriesWriter_UseCompressionOff(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetCompressionLevel(int arg0) {
    SimpleITKPINVOKE.ImageSeriesWriter_SetCompressionLevel(swigCPtr, arg0);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public int GetCompressionLevel() {
    int ret = SimpleITKPINVOKE.ImageSeriesWriter_GetCompressionLevel(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetCompressor(string arg0) {
    SimpleITKPINVOKE.ImageSeriesWriter_SetCompressor(swigCPtr, arg0);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public string GetCompressor() {
    string ret = SimpleITKPINVOKE.ImageSeriesWriter_GetCompressor(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetFileNames(VectorString fileNames) {
    SimpleITKPINVOKE.ImageSeriesWriter_SetFileNames(swigCPtr, VectorString.getCPtr(fileNames));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorString GetFileNames() {
    VectorString ret = new VectorString(SimpleITKPINVOKE.ImageSeriesWriter_GetFileNames(swigCPtr), false);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Execute(Image arg0) {
    SimpleITKPINVOKE.ImageSeriesWriter_Execute__SWIG_0(swigCPtr, Image.getCPtr(arg0));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Execute(Image image, VectorString inFileNames, bool useCompression, int compressionLevel) {
    SimpleITKPINVOKE.ImageSeriesWriter_Execute__SWIG_1(swigCPtr, Image.getCPtr(image), VectorString.getCPtr(inFileNames), useCompression, compressionLevel);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
