//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace itk.simple {

public class ImageReaderBase : ProcessObject {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal ImageReaderBase(global::System.IntPtr cPtr, bool cMemoryOwn) : base(SimpleITKPINVOKE.ImageReaderBase_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ImageReaderBase obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ImageReaderBase obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SimpleITKPINVOKE.delete_ImageReaderBase(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public void SetOutputPixelType(PixelIDValueEnum pixelID) {
    SimpleITKPINVOKE.ImageReaderBase_SetOutputPixelType(swigCPtr, pixelID.swigValue);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public PixelIDValueEnum GetOutputPixelType() {
    PixelIDValueEnum ret = PixelIDValueEnum.swigToEnum(SimpleITKPINVOKE.ImageReaderBase_GetOutputPixelType(swigCPtr));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual Image Execute() {
    Image ret = new Image(SimpleITKPINVOKE.ImageReaderBase_Execute(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string ToString() {
    string ret = SimpleITKPINVOKE.ImageReaderBase_ToString(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual VectorString GetRegisteredImageIOs() {
    VectorString ret = new VectorString(SimpleITKPINVOKE.ImageReaderBase_GetRegisteredImageIOs(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void SetLoadPrivateTags(bool loadPrivateTags) {
    SimpleITKPINVOKE.ImageReaderBase_SetLoadPrivateTags(swigCPtr, loadPrivateTags);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual bool GetLoadPrivateTags() {
    bool ret = SimpleITKPINVOKE.ImageReaderBase_GetLoadPrivateTags(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void LoadPrivateTagsOn() {
    SimpleITKPINVOKE.ImageReaderBase_LoadPrivateTagsOn(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void LoadPrivateTagsOff() {
    SimpleITKPINVOKE.ImageReaderBase_LoadPrivateTagsOff(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void SetImageIO(string imageio) {
    SimpleITKPINVOKE.ImageReaderBase_SetImageIO(swigCPtr, imageio);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual string GetImageIO() {
    string ret = SimpleITKPINVOKE.ImageReaderBase_GetImageIO(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string GetImageIOFromFileName(string fileName) {
    string ret = SimpleITKPINVOKE.ImageReaderBase_GetImageIOFromFileName(fileName);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
