//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace itk.simple {

public class InverseDisplacementFieldImageFilter : ImageFilter {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal InverseDisplacementFieldImageFilter(global::System.IntPtr cPtr, bool cMemoryOwn) : base(SimpleITKPINVOKE.InverseDisplacementFieldImageFilter_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(InverseDisplacementFieldImageFilter obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(InverseDisplacementFieldImageFilter obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SimpleITKPINVOKE.delete_InverseDisplacementFieldImageFilter(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public InverseDisplacementFieldImageFilter() : this(SimpleITKPINVOKE.new_InverseDisplacementFieldImageFilter(), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetSize(VectorUInt32 Size) {
    SimpleITKPINVOKE.InverseDisplacementFieldImageFilter_SetSize(swigCPtr, VectorUInt32.getCPtr(Size));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorUInt32 GetSize() {
    VectorUInt32 ret = new VectorUInt32(SimpleITKPINVOKE.InverseDisplacementFieldImageFilter_GetSize(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetOutputOrigin(VectorDouble OutputOrigin) {
    SimpleITKPINVOKE.InverseDisplacementFieldImageFilter_SetOutputOrigin(swigCPtr, VectorDouble.getCPtr(OutputOrigin));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorDouble GetOutputOrigin() {
    VectorDouble ret = new VectorDouble(SimpleITKPINVOKE.InverseDisplacementFieldImageFilter_GetOutputOrigin(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetOutputSpacing(VectorDouble OutputSpacing) {
    SimpleITKPINVOKE.InverseDisplacementFieldImageFilter_SetOutputSpacing(swigCPtr, VectorDouble.getCPtr(OutputSpacing));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorDouble GetOutputSpacing() {
    VectorDouble ret = new VectorDouble(SimpleITKPINVOKE.InverseDisplacementFieldImageFilter_GetOutputSpacing(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetSubsamplingFactor(uint SubsamplingFactor) {
    SimpleITKPINVOKE.InverseDisplacementFieldImageFilter_SetSubsamplingFactor(swigCPtr, SubsamplingFactor);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint GetSubsamplingFactor() {
    uint ret = SimpleITKPINVOKE.InverseDisplacementFieldImageFilter_GetSubsamplingFactor(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string GetName() {
    string ret = SimpleITKPINVOKE.InverseDisplacementFieldImageFilter_GetName(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string ToString() {
    string ret = SimpleITKPINVOKE.InverseDisplacementFieldImageFilter_ToString(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Image Execute(Image image1) {
    Image ret = new Image(SimpleITKPINVOKE.InverseDisplacementFieldImageFilter_Execute(swigCPtr, Image.getCPtr(image1)), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetReferenceImage(Image refImage) {
    SimpleITKPINVOKE.InverseDisplacementFieldImageFilter_SetReferenceImage(swigCPtr, Image.getCPtr(refImage));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
