//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace itk.simple {

public class IsolatedConnectedImageFilter : ImageFilter {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal IsolatedConnectedImageFilter(global::System.IntPtr cPtr, bool cMemoryOwn) : base(SimpleITKPINVOKE.IsolatedConnectedImageFilter_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IsolatedConnectedImageFilter obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(IsolatedConnectedImageFilter obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SimpleITKPINVOKE.delete_IsolatedConnectedImageFilter(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public IsolatedConnectedImageFilter() : this(SimpleITKPINVOKE.new_IsolatedConnectedImageFilter(), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetSeed1(VectorUInt32 Seed1) {
    SimpleITKPINVOKE.IsolatedConnectedImageFilter_SetSeed1(swigCPtr, VectorUInt32.getCPtr(Seed1));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorUInt32 GetSeed1() {
    VectorUInt32 ret = new VectorUInt32(SimpleITKPINVOKE.IsolatedConnectedImageFilter_GetSeed1(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetSeed2(VectorUInt32 Seed2) {
    SimpleITKPINVOKE.IsolatedConnectedImageFilter_SetSeed2(swigCPtr, VectorUInt32.getCPtr(Seed2));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorUInt32 GetSeed2() {
    VectorUInt32 ret = new VectorUInt32(SimpleITKPINVOKE.IsolatedConnectedImageFilter_GetSeed2(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetLower(double Lower) {
    SimpleITKPINVOKE.IsolatedConnectedImageFilter_SetLower(swigCPtr, Lower);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetLower() {
    double ret = SimpleITKPINVOKE.IsolatedConnectedImageFilter_GetLower(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetUpper(double Upper) {
    SimpleITKPINVOKE.IsolatedConnectedImageFilter_SetUpper(swigCPtr, Upper);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetUpper() {
    double ret = SimpleITKPINVOKE.IsolatedConnectedImageFilter_GetUpper(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetReplaceValue(byte ReplaceValue) {
    SimpleITKPINVOKE.IsolatedConnectedImageFilter_SetReplaceValue(swigCPtr, ReplaceValue);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public byte GetReplaceValue() {
    byte ret = SimpleITKPINVOKE.IsolatedConnectedImageFilter_GetReplaceValue(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetIsolatedValueTolerance(double IsolatedValueTolerance) {
    SimpleITKPINVOKE.IsolatedConnectedImageFilter_SetIsolatedValueTolerance(swigCPtr, IsolatedValueTolerance);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetIsolatedValueTolerance() {
    double ret = SimpleITKPINVOKE.IsolatedConnectedImageFilter_GetIsolatedValueTolerance(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetFindUpperThreshold(bool FindUpperThreshold) {
    SimpleITKPINVOKE.IsolatedConnectedImageFilter_SetFindUpperThreshold(swigCPtr, FindUpperThreshold);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void FindUpperThresholdOn() {
    SimpleITKPINVOKE.IsolatedConnectedImageFilter_FindUpperThresholdOn(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void FindUpperThresholdOff() {
    SimpleITKPINVOKE.IsolatedConnectedImageFilter_FindUpperThresholdOff(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool GetFindUpperThreshold() {
    bool ret = SimpleITKPINVOKE.IsolatedConnectedImageFilter_GetFindUpperThreshold(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool GetThresholdingFailed() {
    bool ret = SimpleITKPINVOKE.IsolatedConnectedImageFilter_GetThresholdingFailed(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetIsolatedValue() {
    double ret = SimpleITKPINVOKE.IsolatedConnectedImageFilter_GetIsolatedValue(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string GetName() {
    string ret = SimpleITKPINVOKE.IsolatedConnectedImageFilter_GetName(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string ToString() {
    string ret = SimpleITKPINVOKE.IsolatedConnectedImageFilter_ToString(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Image Execute(Image image1) {
    Image ret = new Image(SimpleITKPINVOKE.IsolatedConnectedImageFilter_Execute(swigCPtr, Image.getCPtr(image1)), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
