//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace itk.simple {

public sealed class KernelEnum {
  public static readonly KernelEnum sitkAnnulus = new KernelEnum("sitkAnnulus");
  public static readonly KernelEnum sitkBall = new KernelEnum("sitkBall");
  public static readonly KernelEnum sitkBox = new KernelEnum("sitkBox");
  public static readonly KernelEnum sitkCross = new KernelEnum("sitkCross");
  public static readonly KernelEnum sitkPolygon3 = new KernelEnum("sitkPolygon3");
  public static readonly KernelEnum sitkPolygon4 = new KernelEnum("sitkPolygon4");
  public static readonly KernelEnum sitkPolygon5 = new KernelEnum("sitkPolygon5");
  public static readonly KernelEnum sitkPolygon6 = new KernelEnum("sitkPolygon6");
  public static readonly KernelEnum sitkPolygon7 = new KernelEnum("sitkPolygon7");
  public static readonly KernelEnum sitkPolygon8 = new KernelEnum("sitkPolygon8");
  public static readonly KernelEnum sitkPolygon9 = new KernelEnum("sitkPolygon9");

  public readonly int swigValue;

  public static KernelEnum swigToEnum(int swigValue) {
    if (swigValue < swigValues.Length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.Length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new global::System.ArgumentOutOfRangeException("No enum KernelEnum with value " + swigValue);
  }

  public override string ToString() {
    return swigName;
  }

  private KernelEnum(string swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private KernelEnum(string swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private KernelEnum(string swigName, KernelEnum swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static KernelEnum[] swigValues = { sitkAnnulus, sitkBall, sitkBox, sitkCross, sitkPolygon3, sitkPolygon4, sitkPolygon5, sitkPolygon6, sitkPolygon7, sitkPolygon8, sitkPolygon9 };
  private static int swigNext = 0;
  private readonly string swigName;
}

}
