//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace itk.simple {

public class LabelOverlapMeasuresImageFilter : ImageFilter {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal LabelOverlapMeasuresImageFilter(global::System.IntPtr cPtr, bool cMemoryOwn) : base(SimpleITKPINVOKE.LabelOverlapMeasuresImageFilter_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(LabelOverlapMeasuresImageFilter obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(LabelOverlapMeasuresImageFilter obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SimpleITKPINVOKE.delete_LabelOverlapMeasuresImageFilter(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public LabelOverlapMeasuresImageFilter() : this(SimpleITKPINVOKE.new_LabelOverlapMeasuresImageFilter(), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetFalseNegativeError() {
    double ret = SimpleITKPINVOKE.LabelOverlapMeasuresImageFilter_GetFalseNegativeError__SWIG_0(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetFalseNegativeError(long label) {
    double ret = SimpleITKPINVOKE.LabelOverlapMeasuresImageFilter_GetFalseNegativeError__SWIG_1(swigCPtr, label);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetFalsePositiveError() {
    double ret = SimpleITKPINVOKE.LabelOverlapMeasuresImageFilter_GetFalsePositiveError__SWIG_0(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetFalsePositiveError(long label) {
    double ret = SimpleITKPINVOKE.LabelOverlapMeasuresImageFilter_GetFalsePositiveError__SWIG_1(swigCPtr, label);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetMeanOverlap() {
    double ret = SimpleITKPINVOKE.LabelOverlapMeasuresImageFilter_GetMeanOverlap__SWIG_0(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetMeanOverlap(long label) {
    double ret = SimpleITKPINVOKE.LabelOverlapMeasuresImageFilter_GetMeanOverlap__SWIG_1(swigCPtr, label);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetUnionOverlap() {
    double ret = SimpleITKPINVOKE.LabelOverlapMeasuresImageFilter_GetUnionOverlap__SWIG_0(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetUnionOverlap(long label) {
    double ret = SimpleITKPINVOKE.LabelOverlapMeasuresImageFilter_GetUnionOverlap__SWIG_1(swigCPtr, label);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetVolumeSimilarity() {
    double ret = SimpleITKPINVOKE.LabelOverlapMeasuresImageFilter_GetVolumeSimilarity__SWIG_0(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetVolumeSimilarity(long label) {
    double ret = SimpleITKPINVOKE.LabelOverlapMeasuresImageFilter_GetVolumeSimilarity__SWIG_1(swigCPtr, label);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetJaccardCoefficient() {
    double ret = SimpleITKPINVOKE.LabelOverlapMeasuresImageFilter_GetJaccardCoefficient__SWIG_0(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetJaccardCoefficient(long label) {
    double ret = SimpleITKPINVOKE.LabelOverlapMeasuresImageFilter_GetJaccardCoefficient__SWIG_1(swigCPtr, label);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetDiceCoefficient() {
    double ret = SimpleITKPINVOKE.LabelOverlapMeasuresImageFilter_GetDiceCoefficient__SWIG_0(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetDiceCoefficient(long label) {
    double ret = SimpleITKPINVOKE.LabelOverlapMeasuresImageFilter_GetDiceCoefficient__SWIG_1(swigCPtr, label);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetFalseDiscoveryRate() {
    double ret = SimpleITKPINVOKE.LabelOverlapMeasuresImageFilter_GetFalseDiscoveryRate__SWIG_0(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetFalseDiscoveryRate(long label) {
    double ret = SimpleITKPINVOKE.LabelOverlapMeasuresImageFilter_GetFalseDiscoveryRate__SWIG_1(swigCPtr, label);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string GetName() {
    string ret = SimpleITKPINVOKE.LabelOverlapMeasuresImageFilter_GetName(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string ToString() {
    string ret = SimpleITKPINVOKE.LabelOverlapMeasuresImageFilter_ToString(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Execute(Image sourceImage, Image targetImage) {
    SimpleITKPINVOKE.LabelOverlapMeasuresImageFilter_Execute(swigCPtr, Image.getCPtr(sourceImage), Image.getCPtr(targetImage));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
