//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace itk.simple {

public class LabelMapContourOverlayImageFilter : ImageFilter {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal LabelMapContourOverlayImageFilter(global::System.IntPtr cPtr, bool cMemoryOwn) : base(SimpleITKPINVOKE.LabelMapContourOverlayImageFilter_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(LabelMapContourOverlayImageFilter obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(LabelMapContourOverlayImageFilter obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SimpleITKPINVOKE.delete_LabelMapContourOverlayImageFilter(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public LabelMapContourOverlayImageFilter() : this(SimpleITKPINVOKE.new_LabelMapContourOverlayImageFilter(), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetOpacity(double Opacity) {
    SimpleITKPINVOKE.LabelMapContourOverlayImageFilter_SetOpacity(swigCPtr, Opacity);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetOpacity() {
    double ret = SimpleITKPINVOKE.LabelMapContourOverlayImageFilter_GetOpacity(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetDilationRadius(VectorUInt32 DilationRadius) {
    SimpleITKPINVOKE.LabelMapContourOverlayImageFilter_SetDilationRadius__SWIG_0(swigCPtr, VectorUInt32.getCPtr(DilationRadius));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetDilationRadius(uint value) {
    SimpleITKPINVOKE.LabelMapContourOverlayImageFilter_SetDilationRadius__SWIG_1(swigCPtr, value);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorUInt32 GetDilationRadius() {
    VectorUInt32 ret = new VectorUInt32(SimpleITKPINVOKE.LabelMapContourOverlayImageFilter_GetDilationRadius(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetContourThickness(VectorUInt32 ContourThickness) {
    SimpleITKPINVOKE.LabelMapContourOverlayImageFilter_SetContourThickness(swigCPtr, VectorUInt32.getCPtr(ContourThickness));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorUInt32 GetContourThickness() {
    VectorUInt32 ret = new VectorUInt32(SimpleITKPINVOKE.LabelMapContourOverlayImageFilter_GetContourThickness(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetSliceDimension(uint SliceDimension) {
    SimpleITKPINVOKE.LabelMapContourOverlayImageFilter_SetSliceDimension(swigCPtr, SliceDimension);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint GetSliceDimension() {
    uint ret = SimpleITKPINVOKE.LabelMapContourOverlayImageFilter_GetSliceDimension(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetContourType(LabelMapContourOverlayImageFilter.ContourTypeType ContourType) {
    SimpleITKPINVOKE.LabelMapContourOverlayImageFilter_SetContourType(swigCPtr, ContourType.swigValue);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public LabelMapContourOverlayImageFilter.ContourTypeType GetContourType() {
    LabelMapContourOverlayImageFilter.ContourTypeType ret = LabelMapContourOverlayImageFilter.ContourTypeType.swigToEnum(SimpleITKPINVOKE.LabelMapContourOverlayImageFilter_GetContourType(swigCPtr));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetPriority(LabelMapContourOverlayImageFilter.PriorityType Priority) {
    SimpleITKPINVOKE.LabelMapContourOverlayImageFilter_SetPriority(swigCPtr, Priority.swigValue);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public LabelMapContourOverlayImageFilter.PriorityType GetPriority() {
    LabelMapContourOverlayImageFilter.PriorityType ret = LabelMapContourOverlayImageFilter.PriorityType.swigToEnum(SimpleITKPINVOKE.LabelMapContourOverlayImageFilter_GetPriority(swigCPtr));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetColormap(VectorUInt8 Colormap) {
    SimpleITKPINVOKE.LabelMapContourOverlayImageFilter_SetColormap(swigCPtr, VectorUInt8.getCPtr(Colormap));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorUInt8 GetColormap() {
    VectorUInt8 ret = new VectorUInt8(SimpleITKPINVOKE.LabelMapContourOverlayImageFilter_GetColormap(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string GetName() {
    string ret = SimpleITKPINVOKE.LabelMapContourOverlayImageFilter_GetName(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string ToString() {
    string ret = SimpleITKPINVOKE.LabelMapContourOverlayImageFilter_ToString(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Image Execute(Image labelMapImage, Image featureImage) {
    Image ret = new Image(SimpleITKPINVOKE.LabelMapContourOverlayImageFilter_Execute(swigCPtr, Image.getCPtr(labelMapImage), Image.getCPtr(featureImage)), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public sealed class ContourTypeType {
    public static readonly LabelMapContourOverlayImageFilter.ContourTypeType PLAIN = new LabelMapContourOverlayImageFilter.ContourTypeType("PLAIN");
    public static readonly LabelMapContourOverlayImageFilter.ContourTypeType CONTOUR = new LabelMapContourOverlayImageFilter.ContourTypeType("CONTOUR");
    public static readonly LabelMapContourOverlayImageFilter.ContourTypeType SLICE_CONTOUR = new LabelMapContourOverlayImageFilter.ContourTypeType("SLICE_CONTOUR");

    public readonly int swigValue;

    public static ContourTypeType swigToEnum(int swigValue) {
      if (swigValue < swigValues.Length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.Length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new global::System.ArgumentOutOfRangeException("No enum ContourTypeType with value " + swigValue);
    }

    public override string ToString() {
      return swigName;
    }

    private ContourTypeType(string swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private ContourTypeType(string swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private ContourTypeType(string swigName, ContourTypeType swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static ContourTypeType[] swigValues = { PLAIN, CONTOUR, SLICE_CONTOUR };
    private static int swigNext = 0;
    private readonly string swigName;
  }

  public sealed class PriorityType {
    public static readonly LabelMapContourOverlayImageFilter.PriorityType HIGH_LABEL_ON_TOP = new LabelMapContourOverlayImageFilter.PriorityType("HIGH_LABEL_ON_TOP");
    public static readonly LabelMapContourOverlayImageFilter.PriorityType LOW_LABEL_ON_TOP = new LabelMapContourOverlayImageFilter.PriorityType("LOW_LABEL_ON_TOP");

    public readonly int swigValue;

    public static PriorityType swigToEnum(int swigValue) {
      if (swigValue < swigValues.Length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.Length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new global::System.ArgumentOutOfRangeException("No enum PriorityType with value " + swigValue);
    }

    public override string ToString() {
      return swigName;
    }

    private PriorityType(string swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private PriorityType(string swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private PriorityType(string swigName, PriorityType swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static PriorityType[] swigValues = { HIGH_LABEL_ON_TOP, LOW_LABEL_ON_TOP };
    private static int swigNext = 0;
    private readonly string swigName;
  }

}

}
