//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace itk.simple {

public class LevelSetMotionRegistrationFilter : ImageFilter {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal LevelSetMotionRegistrationFilter(global::System.IntPtr cPtr, bool cMemoryOwn) : base(SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(LevelSetMotionRegistrationFilter obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(LevelSetMotionRegistrationFilter obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SimpleITKPINVOKE.delete_LevelSetMotionRegistrationFilter(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public LevelSetMotionRegistrationFilter() : this(SimpleITKPINVOKE.new_LevelSetMotionRegistrationFilter(), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetGradientSmoothingStandardDeviations(double GradientSmoothingStandardDeviations) {
    SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_SetGradientSmoothingStandardDeviations(swigCPtr, GradientSmoothingStandardDeviations);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetGradientSmoothingStandardDeviations() {
    double ret = SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_GetGradientSmoothingStandardDeviations(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetNumberOfIterations(uint NumberOfIterations) {
    SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_SetNumberOfIterations(swigCPtr, NumberOfIterations);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint GetNumberOfIterations() {
    uint ret = SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_GetNumberOfIterations(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetMaximumRMSError(double MaximumRMSError) {
    SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_SetMaximumRMSError(swigCPtr, MaximumRMSError);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetMaximumRMSError() {
    double ret = SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_GetMaximumRMSError(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetStandardDeviations(VectorDouble StandardDeviations) {
    SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_SetStandardDeviations__SWIG_0(swigCPtr, VectorDouble.getCPtr(StandardDeviations));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetStandardDeviations(double value) {
    SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_SetStandardDeviations__SWIG_1(swigCPtr, value);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorDouble GetStandardDeviations() {
    VectorDouble ret = new VectorDouble(SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_GetStandardDeviations(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetSmoothDisplacementField(bool SmoothDisplacementField) {
    SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_SetSmoothDisplacementField(swigCPtr, SmoothDisplacementField);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SmoothDisplacementFieldOn() {
    SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_SmoothDisplacementFieldOn(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SmoothDisplacementFieldOff() {
    SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_SmoothDisplacementFieldOff(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool GetSmoothDisplacementField() {
    bool ret = SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_GetSmoothDisplacementField(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetUpdateFieldStandardDeviations(VectorDouble UpdateFieldStandardDeviations) {
    SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_SetUpdateFieldStandardDeviations__SWIG_0(swigCPtr, VectorDouble.getCPtr(UpdateFieldStandardDeviations));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetUpdateFieldStandardDeviations(double value) {
    SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_SetUpdateFieldStandardDeviations__SWIG_1(swigCPtr, value);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorDouble GetUpdateFieldStandardDeviations() {
    VectorDouble ret = new VectorDouble(SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_GetUpdateFieldStandardDeviations(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetSmoothUpdateField(bool SmoothUpdateField) {
    SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_SetSmoothUpdateField(swigCPtr, SmoothUpdateField);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SmoothUpdateFieldOn() {
    SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_SmoothUpdateFieldOn(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SmoothUpdateFieldOff() {
    SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_SmoothUpdateFieldOff(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool GetSmoothUpdateField() {
    bool ret = SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_GetSmoothUpdateField(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetMaximumKernelWidth(uint MaximumKernelWidth) {
    SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_SetMaximumKernelWidth(swigCPtr, MaximumKernelWidth);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint GetMaximumKernelWidth() {
    uint ret = SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_GetMaximumKernelWidth(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetMaximumError(double MaximumError) {
    SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_SetMaximumError(swigCPtr, MaximumError);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetMaximumError() {
    double ret = SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_GetMaximumError(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetAlpha(double Alpha) {
    SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_SetAlpha(swigCPtr, Alpha);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetAlpha() {
    double ret = SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_GetAlpha(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetIntensityDifferenceThreshold(double IntensityDifferenceThreshold) {
    SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_SetIntensityDifferenceThreshold(swigCPtr, IntensityDifferenceThreshold);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetIntensityDifferenceThreshold() {
    double ret = SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_GetIntensityDifferenceThreshold(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetGradientMagnitudeThreshold(double GradientMagnitudeThreshold) {
    SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_SetGradientMagnitudeThreshold(swigCPtr, GradientMagnitudeThreshold);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetGradientMagnitudeThreshold() {
    double ret = SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_GetGradientMagnitudeThreshold(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetUseImageSpacing(bool UseImageSpacing) {
    SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_SetUseImageSpacing(swigCPtr, UseImageSpacing);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void UseImageSpacingOn() {
    SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_UseImageSpacingOn(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void UseImageSpacingOff() {
    SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_UseImageSpacingOff(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool GetUseImageSpacing() {
    bool ret = SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_GetUseImageSpacing(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public uint GetElapsedIterations() {
    uint ret = SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_GetElapsedIterations(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetRMSChange() {
    double ret = SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_GetRMSChange(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetMetric() {
    double ret = SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_GetMetric(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string GetName() {
    string ret = SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_GetName(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string ToString() {
    string ret = SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_ToString(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Image Execute(Image fixedImage, Image movingImage, Image initialDisplacementField) {
    Image ret = new Image(SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_Execute__SWIG_0(swigCPtr, Image.getCPtr(fixedImage), Image.getCPtr(movingImage), Image.getCPtr(initialDisplacementField)), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Image Execute(Image fixedImage, Image movingImage) {
    Image ret = new Image(SimpleITKPINVOKE.LevelSetMotionRegistrationFilter_Execute__SWIG_1(swigCPtr, Image.getCPtr(fixedImage), Image.getCPtr(movingImage)), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
