//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace itk.simple {

public class MaskedFFTNormalizedCorrelationImageFilter : ImageFilter {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal MaskedFFTNormalizedCorrelationImageFilter(global::System.IntPtr cPtr, bool cMemoryOwn) : base(SimpleITKPINVOKE.MaskedFFTNormalizedCorrelationImageFilter_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MaskedFFTNormalizedCorrelationImageFilter obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(MaskedFFTNormalizedCorrelationImageFilter obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SimpleITKPINVOKE.delete_MaskedFFTNormalizedCorrelationImageFilter(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public MaskedFFTNormalizedCorrelationImageFilter() : this(SimpleITKPINVOKE.new_MaskedFFTNormalizedCorrelationImageFilter(), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRequiredNumberOfOverlappingPixels(ulong RequiredNumberOfOverlappingPixels) {
    SimpleITKPINVOKE.MaskedFFTNormalizedCorrelationImageFilter_SetRequiredNumberOfOverlappingPixels(swigCPtr, RequiredNumberOfOverlappingPixels);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public ulong GetRequiredNumberOfOverlappingPixels() {
    ulong ret = SimpleITKPINVOKE.MaskedFFTNormalizedCorrelationImageFilter_GetRequiredNumberOfOverlappingPixels(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetRequiredFractionOfOverlappingPixels(float RequiredFractionOfOverlappingPixels) {
    SimpleITKPINVOKE.MaskedFFTNormalizedCorrelationImageFilter_SetRequiredFractionOfOverlappingPixels(swigCPtr, RequiredFractionOfOverlappingPixels);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public float GetRequiredFractionOfOverlappingPixels() {
    float ret = SimpleITKPINVOKE.MaskedFFTNormalizedCorrelationImageFilter_GetRequiredFractionOfOverlappingPixels(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string GetName() {
    string ret = SimpleITKPINVOKE.MaskedFFTNormalizedCorrelationImageFilter_GetName(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string ToString() {
    string ret = SimpleITKPINVOKE.MaskedFFTNormalizedCorrelationImageFilter_ToString(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Image Execute(Image fixedImage, Image movingImage, Image fixedImageMask, Image movingImageMask) {
    Image ret = new Image(SimpleITKPINVOKE.MaskedFFTNormalizedCorrelationImageFilter_Execute(swigCPtr, Image.getCPtr(fixedImage), Image.getCPtr(movingImage), Image.getCPtr(fixedImageMask), Image.getCPtr(movingImageMask)), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
