//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace itk.simple {

public class PatchBasedDenoisingImageFilter : ImageFilter {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal PatchBasedDenoisingImageFilter(global::System.IntPtr cPtr, bool cMemoryOwn) : base(SimpleITKPINVOKE.PatchBasedDenoisingImageFilter_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PatchBasedDenoisingImageFilter obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(PatchBasedDenoisingImageFilter obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SimpleITKPINVOKE.delete_PatchBasedDenoisingImageFilter(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public PatchBasedDenoisingImageFilter() : this(SimpleITKPINVOKE.new_PatchBasedDenoisingImageFilter(), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetKernelBandwidthSigma(double KernelBandwidthSigma) {
    SimpleITKPINVOKE.PatchBasedDenoisingImageFilter_SetKernelBandwidthSigma(swigCPtr, KernelBandwidthSigma);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetKernelBandwidthSigma() {
    double ret = SimpleITKPINVOKE.PatchBasedDenoisingImageFilter_GetKernelBandwidthSigma(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetPatchRadius(uint PatchRadius) {
    SimpleITKPINVOKE.PatchBasedDenoisingImageFilter_SetPatchRadius(swigCPtr, PatchRadius);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint GetPatchRadius() {
    uint ret = SimpleITKPINVOKE.PatchBasedDenoisingImageFilter_GetPatchRadius(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetNumberOfIterations(uint NumberOfIterations) {
    SimpleITKPINVOKE.PatchBasedDenoisingImageFilter_SetNumberOfIterations(swigCPtr, NumberOfIterations);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint GetNumberOfIterations() {
    uint ret = SimpleITKPINVOKE.PatchBasedDenoisingImageFilter_GetNumberOfIterations(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetNumberOfSamplePatches(uint NumberOfSamplePatches) {
    SimpleITKPINVOKE.PatchBasedDenoisingImageFilter_SetNumberOfSamplePatches(swigCPtr, NumberOfSamplePatches);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint GetNumberOfSamplePatches() {
    uint ret = SimpleITKPINVOKE.PatchBasedDenoisingImageFilter_GetNumberOfSamplePatches(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetSampleVariance(double SampleVariance) {
    SimpleITKPINVOKE.PatchBasedDenoisingImageFilter_SetSampleVariance(swigCPtr, SampleVariance);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetSampleVariance() {
    double ret = SimpleITKPINVOKE.PatchBasedDenoisingImageFilter_GetSampleVariance(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetNoiseModel(PatchBasedDenoisingImageFilter.NoiseModelType NoiseModel) {
    SimpleITKPINVOKE.PatchBasedDenoisingImageFilter_SetNoiseModel(swigCPtr, NoiseModel.swigValue);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public PatchBasedDenoisingImageFilter.NoiseModelType GetNoiseModel() {
    PatchBasedDenoisingImageFilter.NoiseModelType ret = PatchBasedDenoisingImageFilter.NoiseModelType.swigToEnum(SimpleITKPINVOKE.PatchBasedDenoisingImageFilter_GetNoiseModel(swigCPtr));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetNoiseSigma(double NoiseSigma) {
    SimpleITKPINVOKE.PatchBasedDenoisingImageFilter_SetNoiseSigma(swigCPtr, NoiseSigma);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetNoiseSigma() {
    double ret = SimpleITKPINVOKE.PatchBasedDenoisingImageFilter_GetNoiseSigma(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetNoiseModelFidelityWeight(double NoiseModelFidelityWeight) {
    SimpleITKPINVOKE.PatchBasedDenoisingImageFilter_SetNoiseModelFidelityWeight(swigCPtr, NoiseModelFidelityWeight);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetNoiseModelFidelityWeight() {
    double ret = SimpleITKPINVOKE.PatchBasedDenoisingImageFilter_GetNoiseModelFidelityWeight(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetAlwaysTreatComponentsAsEuclidean(bool AlwaysTreatComponentsAsEuclidean) {
    SimpleITKPINVOKE.PatchBasedDenoisingImageFilter_SetAlwaysTreatComponentsAsEuclidean(swigCPtr, AlwaysTreatComponentsAsEuclidean);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AlwaysTreatComponentsAsEuclideanOn() {
    SimpleITKPINVOKE.PatchBasedDenoisingImageFilter_AlwaysTreatComponentsAsEuclideanOn(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AlwaysTreatComponentsAsEuclideanOff() {
    SimpleITKPINVOKE.PatchBasedDenoisingImageFilter_AlwaysTreatComponentsAsEuclideanOff(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool GetAlwaysTreatComponentsAsEuclidean() {
    bool ret = SimpleITKPINVOKE.PatchBasedDenoisingImageFilter_GetAlwaysTreatComponentsAsEuclidean(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetKernelBandwidthEstimation(bool KernelBandwidthEstimation) {
    SimpleITKPINVOKE.PatchBasedDenoisingImageFilter_SetKernelBandwidthEstimation(swigCPtr, KernelBandwidthEstimation);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void KernelBandwidthEstimationOn() {
    SimpleITKPINVOKE.PatchBasedDenoisingImageFilter_KernelBandwidthEstimationOn(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void KernelBandwidthEstimationOff() {
    SimpleITKPINVOKE.PatchBasedDenoisingImageFilter_KernelBandwidthEstimationOff(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool GetKernelBandwidthEstimation() {
    bool ret = SimpleITKPINVOKE.PatchBasedDenoisingImageFilter_GetKernelBandwidthEstimation(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetKernelBandwidthMultiplicationFactor(double KernelBandwidthMultiplicationFactor) {
    SimpleITKPINVOKE.PatchBasedDenoisingImageFilter_SetKernelBandwidthMultiplicationFactor(swigCPtr, KernelBandwidthMultiplicationFactor);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetKernelBandwidthMultiplicationFactor() {
    double ret = SimpleITKPINVOKE.PatchBasedDenoisingImageFilter_GetKernelBandwidthMultiplicationFactor(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetKernelBandwidthUpdateFrequency(uint KernelBandwidthUpdateFrequency) {
    SimpleITKPINVOKE.PatchBasedDenoisingImageFilter_SetKernelBandwidthUpdateFrequency(swigCPtr, KernelBandwidthUpdateFrequency);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint GetKernelBandwidthUpdateFrequency() {
    uint ret = SimpleITKPINVOKE.PatchBasedDenoisingImageFilter_GetKernelBandwidthUpdateFrequency(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetKernelBandwidthFractionPixelsForEstimation(double KernelBandwidthFractionPixelsForEstimation) {
    SimpleITKPINVOKE.PatchBasedDenoisingImageFilter_SetKernelBandwidthFractionPixelsForEstimation(swigCPtr, KernelBandwidthFractionPixelsForEstimation);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetKernelBandwidthFractionPixelsForEstimation() {
    double ret = SimpleITKPINVOKE.PatchBasedDenoisingImageFilter_GetKernelBandwidthFractionPixelsForEstimation(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string GetName() {
    string ret = SimpleITKPINVOKE.PatchBasedDenoisingImageFilter_GetName(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string ToString() {
    string ret = SimpleITKPINVOKE.PatchBasedDenoisingImageFilter_ToString(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Image Execute(Image image1) {
    Image ret = new Image(SimpleITKPINVOKE.PatchBasedDenoisingImageFilter_Execute(swigCPtr, Image.getCPtr(image1)), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public sealed class NoiseModelType {
    public static readonly PatchBasedDenoisingImageFilter.NoiseModelType NOMODEL = new PatchBasedDenoisingImageFilter.NoiseModelType("NOMODEL");
    public static readonly PatchBasedDenoisingImageFilter.NoiseModelType GAUSSIAN = new PatchBasedDenoisingImageFilter.NoiseModelType("GAUSSIAN");
    public static readonly PatchBasedDenoisingImageFilter.NoiseModelType RICIAN = new PatchBasedDenoisingImageFilter.NoiseModelType("RICIAN");
    public static readonly PatchBasedDenoisingImageFilter.NoiseModelType POISSON = new PatchBasedDenoisingImageFilter.NoiseModelType("POISSON");

    public readonly int swigValue;

    public static NoiseModelType swigToEnum(int swigValue) {
      if (swigValue < swigValues.Length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.Length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new global::System.ArgumentOutOfRangeException("No enum NoiseModelType with value " + swigValue);
    }

    public override string ToString() {
      return swigName;
    }

    private NoiseModelType(string swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private NoiseModelType(string swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private NoiseModelType(string swigName, NoiseModelType swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static NoiseModelType[] swigValues = { NOMODEL, GAUSSIAN, RICIAN, POISSON };
    private static int swigNext = 0;
    private readonly string swigName;
  }

}

}
