//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace itk.simple {

public class RichardsonLucyDeconvolutionImageFilter : ImageFilter {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal RichardsonLucyDeconvolutionImageFilter(global::System.IntPtr cPtr, bool cMemoryOwn) : base(SimpleITKPINVOKE.RichardsonLucyDeconvolutionImageFilter_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RichardsonLucyDeconvolutionImageFilter obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(RichardsonLucyDeconvolutionImageFilter obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SimpleITKPINVOKE.delete_RichardsonLucyDeconvolutionImageFilter(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public RichardsonLucyDeconvolutionImageFilter() : this(SimpleITKPINVOKE.new_RichardsonLucyDeconvolutionImageFilter(), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetNumberOfIterations(int NumberOfIterations) {
    SimpleITKPINVOKE.RichardsonLucyDeconvolutionImageFilter_SetNumberOfIterations(swigCPtr, NumberOfIterations);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public int GetNumberOfIterations() {
    int ret = SimpleITKPINVOKE.RichardsonLucyDeconvolutionImageFilter_GetNumberOfIterations(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetNormalize(bool Normalize) {
    SimpleITKPINVOKE.RichardsonLucyDeconvolutionImageFilter_SetNormalize(swigCPtr, Normalize);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void NormalizeOn() {
    SimpleITKPINVOKE.RichardsonLucyDeconvolutionImageFilter_NormalizeOn(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void NormalizeOff() {
    SimpleITKPINVOKE.RichardsonLucyDeconvolutionImageFilter_NormalizeOff(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool GetNormalize() {
    bool ret = SimpleITKPINVOKE.RichardsonLucyDeconvolutionImageFilter_GetNormalize(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetBoundaryCondition(RichardsonLucyDeconvolutionImageFilter.BoundaryConditionType BoundaryCondition) {
    SimpleITKPINVOKE.RichardsonLucyDeconvolutionImageFilter_SetBoundaryCondition(swigCPtr, BoundaryCondition.swigValue);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public RichardsonLucyDeconvolutionImageFilter.BoundaryConditionType GetBoundaryCondition() {
    RichardsonLucyDeconvolutionImageFilter.BoundaryConditionType ret = RichardsonLucyDeconvolutionImageFilter.BoundaryConditionType.swigToEnum(SimpleITKPINVOKE.RichardsonLucyDeconvolutionImageFilter_GetBoundaryCondition(swigCPtr));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetOutputRegionMode(RichardsonLucyDeconvolutionImageFilter.OutputRegionModeType OutputRegionMode) {
    SimpleITKPINVOKE.RichardsonLucyDeconvolutionImageFilter_SetOutputRegionMode(swigCPtr, OutputRegionMode.swigValue);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public RichardsonLucyDeconvolutionImageFilter.OutputRegionModeType GetOutputRegionMode() {
    RichardsonLucyDeconvolutionImageFilter.OutputRegionModeType ret = RichardsonLucyDeconvolutionImageFilter.OutputRegionModeType.swigToEnum(SimpleITKPINVOKE.RichardsonLucyDeconvolutionImageFilter_GetOutputRegionMode(swigCPtr));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string GetName() {
    string ret = SimpleITKPINVOKE.RichardsonLucyDeconvolutionImageFilter_GetName(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string ToString() {
    string ret = SimpleITKPINVOKE.RichardsonLucyDeconvolutionImageFilter_ToString(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Image Execute(Image image1, Image image2) {
    Image ret = new Image(SimpleITKPINVOKE.RichardsonLucyDeconvolutionImageFilter_Execute(swigCPtr, Image.getCPtr(image1), Image.getCPtr(image2)), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public sealed class BoundaryConditionType {
    public static readonly RichardsonLucyDeconvolutionImageFilter.BoundaryConditionType ZERO_PAD = new RichardsonLucyDeconvolutionImageFilter.BoundaryConditionType("ZERO_PAD");
    public static readonly RichardsonLucyDeconvolutionImageFilter.BoundaryConditionType ZERO_FLUX_NEUMANN_PAD = new RichardsonLucyDeconvolutionImageFilter.BoundaryConditionType("ZERO_FLUX_NEUMANN_PAD");
    public static readonly RichardsonLucyDeconvolutionImageFilter.BoundaryConditionType PERIODIC_PAD = new RichardsonLucyDeconvolutionImageFilter.BoundaryConditionType("PERIODIC_PAD");

    public readonly int swigValue;

    public static BoundaryConditionType swigToEnum(int swigValue) {
      if (swigValue < swigValues.Length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.Length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new global::System.ArgumentOutOfRangeException("No enum BoundaryConditionType with value " + swigValue);
    }

    public override string ToString() {
      return swigName;
    }

    private BoundaryConditionType(string swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private BoundaryConditionType(string swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private BoundaryConditionType(string swigName, BoundaryConditionType swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static BoundaryConditionType[] swigValues = { ZERO_PAD, ZERO_FLUX_NEUMANN_PAD, PERIODIC_PAD };
    private static int swigNext = 0;
    private readonly string swigName;
  }

  public sealed class OutputRegionModeType {
    public static readonly RichardsonLucyDeconvolutionImageFilter.OutputRegionModeType SAME = new RichardsonLucyDeconvolutionImageFilter.OutputRegionModeType("SAME");
    public static readonly RichardsonLucyDeconvolutionImageFilter.OutputRegionModeType VALID = new RichardsonLucyDeconvolutionImageFilter.OutputRegionModeType("VALID");

    public readonly int swigValue;

    public static OutputRegionModeType swigToEnum(int swigValue) {
      if (swigValue < swigValues.Length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.Length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new global::System.ArgumentOutOfRangeException("No enum OutputRegionModeType with value " + swigValue);
    }

    public override string ToString() {
      return swigName;
    }

    private OutputRegionModeType(string swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private OutputRegionModeType(string swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private OutputRegionModeType(string swigName, OutputRegionModeType swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static OutputRegionModeType[] swigValues = { SAME, VALID };
    private static int swigNext = 0;
    private readonly string swigName;
  }

}

}
