//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace itk.simple {

public class ScaleVersor3DTransform : Transform {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal ScaleVersor3DTransform(global::System.IntPtr cPtr, bool cMemoryOwn) : base(SimpleITKPINVOKE.ScaleVersor3DTransform_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ScaleVersor3DTransform obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ScaleVersor3DTransform obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SimpleITKPINVOKE.delete_ScaleVersor3DTransform(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public ScaleVersor3DTransform() : this(SimpleITKPINVOKE.new_ScaleVersor3DTransform__SWIG_0(), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public ScaleVersor3DTransform(ScaleVersor3DTransform arg0) : this(SimpleITKPINVOKE.new_ScaleVersor3DTransform__SWIG_1(ScaleVersor3DTransform.getCPtr(arg0)), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public ScaleVersor3DTransform(Transform arg0) : this(SimpleITKPINVOKE.new_ScaleVersor3DTransform__SWIG_2(Transform.getCPtr(arg0)), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public ScaleVersor3DTransform(VectorDouble scale, VectorDouble versor, VectorDouble translation, VectorDouble fixedCenter) : this(SimpleITKPINVOKE.new_ScaleVersor3DTransform__SWIG_3(VectorDouble.getCPtr(scale), VectorDouble.getCPtr(versor), VectorDouble.getCPtr(translation), VectorDouble.getCPtr(fixedCenter)), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public ScaleVersor3DTransform(VectorDouble scale, VectorDouble versor, VectorDouble translation) : this(SimpleITKPINVOKE.new_ScaleVersor3DTransform__SWIG_4(VectorDouble.getCPtr(scale), VectorDouble.getCPtr(versor), VectorDouble.getCPtr(translation)), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public ScaleVersor3DTransform(VectorDouble scale, VectorDouble versor) : this(SimpleITKPINVOKE.new_ScaleVersor3DTransform__SWIG_5(VectorDouble.getCPtr(scale), VectorDouble.getCPtr(versor)), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public ScaleVersor3DTransform(VectorDouble scale, VectorDouble axis, double angle, VectorDouble translation, VectorDouble fixedCenter) : this(SimpleITKPINVOKE.new_ScaleVersor3DTransform__SWIG_6(VectorDouble.getCPtr(scale), VectorDouble.getCPtr(axis), angle, VectorDouble.getCPtr(translation), VectorDouble.getCPtr(fixedCenter)), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public ScaleVersor3DTransform(VectorDouble scale, VectorDouble axis, double angle, VectorDouble translation) : this(SimpleITKPINVOKE.new_ScaleVersor3DTransform__SWIG_7(VectorDouble.getCPtr(scale), VectorDouble.getCPtr(axis), angle, VectorDouble.getCPtr(translation)), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public ScaleVersor3DTransform(VectorDouble scale, VectorDouble axis, double angle) : this(SimpleITKPINVOKE.new_ScaleVersor3DTransform__SWIG_8(VectorDouble.getCPtr(scale), VectorDouble.getCPtr(axis), angle), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public override string GetName() {
    string ret = SimpleITKPINVOKE.ScaleVersor3DTransform_GetName(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetCenter(VectorDouble params_) {
    SimpleITKPINVOKE.ScaleVersor3DTransform_SetCenter(swigCPtr, VectorDouble.getCPtr(params_));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorDouble GetCenter() {
    VectorDouble ret = new VectorDouble(SimpleITKPINVOKE.ScaleVersor3DTransform_GetCenter(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetRotation(VectorDouble versor) {
    SimpleITKPINVOKE.ScaleVersor3DTransform_SetRotation__SWIG_0(swigCPtr, VectorDouble.getCPtr(versor));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRotation(VectorDouble axis, double angle) {
    SimpleITKPINVOKE.ScaleVersor3DTransform_SetRotation__SWIG_1(swigCPtr, VectorDouble.getCPtr(axis), angle);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorDouble GetVersor() {
    VectorDouble ret = new VectorDouble(SimpleITKPINVOKE.ScaleVersor3DTransform_GetVersor(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public VectorDouble GetTranslation() {
    VectorDouble ret = new VectorDouble(SimpleITKPINVOKE.ScaleVersor3DTransform_GetTranslation(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetTranslation(VectorDouble translation) {
    SimpleITKPINVOKE.ScaleVersor3DTransform_SetTranslation(swigCPtr, VectorDouble.getCPtr(translation));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorDouble GetScale() {
    VectorDouble ret = new VectorDouble(SimpleITKPINVOKE.ScaleVersor3DTransform_GetScale(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetScale(VectorDouble scale) {
    SimpleITKPINVOKE.ScaleVersor3DTransform_SetScale(swigCPtr, VectorDouble.getCPtr(scale));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Translate(VectorDouble offset) {
    SimpleITKPINVOKE.ScaleVersor3DTransform_Translate(swigCPtr, VectorDouble.getCPtr(offset));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorDouble GetMatrix() {
    VectorDouble ret = new VectorDouble(SimpleITKPINVOKE.ScaleVersor3DTransform_GetMatrix(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
