//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace itk.simple {

public class ScaleTransform : Transform {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal ScaleTransform(global::System.IntPtr cPtr, bool cMemoryOwn) : base(SimpleITKPINVOKE.ScaleTransform_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ScaleTransform obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ScaleTransform obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SimpleITKPINVOKE.delete_ScaleTransform(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public ScaleTransform(uint dimensions, VectorDouble scale) : this(SimpleITKPINVOKE.new_ScaleTransform__SWIG_0(dimensions, VectorDouble.getCPtr(scale)), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public ScaleTransform(uint dimensions) : this(SimpleITKPINVOKE.new_ScaleTransform__SWIG_1(dimensions), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public ScaleTransform(ScaleTransform arg0) : this(SimpleITKPINVOKE.new_ScaleTransform__SWIG_2(ScaleTransform.getCPtr(arg0)), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public ScaleTransform(Transform arg0) : this(SimpleITKPINVOKE.new_ScaleTransform__SWIG_3(Transform.getCPtr(arg0)), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public override string GetName() {
    string ret = SimpleITKPINVOKE.ScaleTransform_GetName(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetScale(VectorDouble params_) {
    SimpleITKPINVOKE.ScaleTransform_SetScale(swigCPtr, VectorDouble.getCPtr(params_));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorDouble GetScale() {
    VectorDouble ret = new VectorDouble(SimpleITKPINVOKE.ScaleTransform_GetScale(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetCenter(VectorDouble params_) {
    SimpleITKPINVOKE.ScaleTransform_SetCenter(swigCPtr, VectorDouble.getCPtr(params_));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorDouble GetCenter() {
    VectorDouble ret = new VectorDouble(SimpleITKPINVOKE.ScaleTransform_GetCenter(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public VectorDouble GetMatrix() {
    VectorDouble ret = new VectorDouble(SimpleITKPINVOKE.ScaleTransform_GetMatrix(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
