//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace itk.simple {

public class Similarity3DTransform : Transform {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal Similarity3DTransform(global::System.IntPtr cPtr, bool cMemoryOwn) : base(SimpleITKPINVOKE.Similarity3DTransform_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Similarity3DTransform obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Similarity3DTransform obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SimpleITKPINVOKE.delete_Similarity3DTransform(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public Similarity3DTransform() : this(SimpleITKPINVOKE.new_Similarity3DTransform__SWIG_0(), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public Similarity3DTransform(Similarity3DTransform arg0) : this(SimpleITKPINVOKE.new_Similarity3DTransform__SWIG_1(Similarity3DTransform.getCPtr(arg0)), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public Similarity3DTransform(Transform arg0) : this(SimpleITKPINVOKE.new_Similarity3DTransform__SWIG_2(Transform.getCPtr(arg0)), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public Similarity3DTransform(double scaleFactor, VectorDouble versor, VectorDouble translation, VectorDouble fixedCenter) : this(SimpleITKPINVOKE.new_Similarity3DTransform__SWIG_3(scaleFactor, VectorDouble.getCPtr(versor), VectorDouble.getCPtr(translation), VectorDouble.getCPtr(fixedCenter)), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public Similarity3DTransform(double scaleFactor, VectorDouble versor, VectorDouble translation) : this(SimpleITKPINVOKE.new_Similarity3DTransform__SWIG_4(scaleFactor, VectorDouble.getCPtr(versor), VectorDouble.getCPtr(translation)), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public Similarity3DTransform(double scaleFactor, VectorDouble versor) : this(SimpleITKPINVOKE.new_Similarity3DTransform__SWIG_5(scaleFactor, VectorDouble.getCPtr(versor)), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public Similarity3DTransform(double scaleFactor, VectorDouble axis, double angle, VectorDouble translation, VectorDouble fixedCenter) : this(SimpleITKPINVOKE.new_Similarity3DTransform__SWIG_6(scaleFactor, VectorDouble.getCPtr(axis), angle, VectorDouble.getCPtr(translation), VectorDouble.getCPtr(fixedCenter)), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public Similarity3DTransform(double scaleFactor, VectorDouble axis, double angle, VectorDouble translation) : this(SimpleITKPINVOKE.new_Similarity3DTransform__SWIG_7(scaleFactor, VectorDouble.getCPtr(axis), angle, VectorDouble.getCPtr(translation)), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public Similarity3DTransform(double scaleFactor, VectorDouble axis, double angle) : this(SimpleITKPINVOKE.new_Similarity3DTransform__SWIG_8(scaleFactor, VectorDouble.getCPtr(axis), angle), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public override string GetName() {
    string ret = SimpleITKPINVOKE.Similarity3DTransform_GetName(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetCenter(VectorDouble params_) {
    SimpleITKPINVOKE.Similarity3DTransform_SetCenter(swigCPtr, VectorDouble.getCPtr(params_));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorDouble GetCenter() {
    VectorDouble ret = new VectorDouble(SimpleITKPINVOKE.Similarity3DTransform_GetCenter(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetRotation(VectorDouble versor) {
    SimpleITKPINVOKE.Similarity3DTransform_SetRotation__SWIG_0(swigCPtr, VectorDouble.getCPtr(versor));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRotation(VectorDouble axis, double angle) {
    SimpleITKPINVOKE.Similarity3DTransform_SetRotation__SWIG_1(swigCPtr, VectorDouble.getCPtr(axis), angle);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorDouble GetVersor() {
    VectorDouble ret = new VectorDouble(SimpleITKPINVOKE.Similarity3DTransform_GetVersor(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetScale(double scale) {
    SimpleITKPINVOKE.Similarity3DTransform_SetScale(swigCPtr, scale);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetScale() {
    double ret = SimpleITKPINVOKE.Similarity3DTransform_GetScale(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public VectorDouble GetTranslation() {
    VectorDouble ret = new VectorDouble(SimpleITKPINVOKE.Similarity3DTransform_GetTranslation(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetTranslation(VectorDouble translation) {
    SimpleITKPINVOKE.Similarity3DTransform_SetTranslation(swigCPtr, VectorDouble.getCPtr(translation));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Translate(VectorDouble offset) {
    SimpleITKPINVOKE.Similarity3DTransform_Translate(swigCPtr, VectorDouble.getCPtr(offset));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorDouble GetMatrix() {
    VectorDouble ret = new VectorDouble(SimpleITKPINVOKE.Similarity3DTransform_GetMatrix(swigCPtr), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetMatrix(VectorDouble matrix, double tolerance) {
    SimpleITKPINVOKE.Similarity3DTransform_SetMatrix__SWIG_0(swigCPtr, VectorDouble.getCPtr(matrix), tolerance);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetMatrix(VectorDouble matrix) {
    SimpleITKPINVOKE.Similarity3DTransform_SetMatrix__SWIG_1(swigCPtr, VectorDouble.getCPtr(matrix));
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
