//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace itk.simple {

public class ThresholdMaximumConnectedComponentsImageFilter : ImageFilter {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal ThresholdMaximumConnectedComponentsImageFilter(global::System.IntPtr cPtr, bool cMemoryOwn) : base(SimpleITKPINVOKE.ThresholdMaximumConnectedComponentsImageFilter_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ThresholdMaximumConnectedComponentsImageFilter obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ThresholdMaximumConnectedComponentsImageFilter obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SimpleITKPINVOKE.delete_ThresholdMaximumConnectedComponentsImageFilter(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public ThresholdMaximumConnectedComponentsImageFilter() : this(SimpleITKPINVOKE.new_ThresholdMaximumConnectedComponentsImageFilter(), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetMinimumObjectSizeInPixels(uint MinimumObjectSizeInPixels) {
    SimpleITKPINVOKE.ThresholdMaximumConnectedComponentsImageFilter_SetMinimumObjectSizeInPixels(swigCPtr, MinimumObjectSizeInPixels);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint GetMinimumObjectSizeInPixels() {
    uint ret = SimpleITKPINVOKE.ThresholdMaximumConnectedComponentsImageFilter_GetMinimumObjectSizeInPixels(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetUpperBoundary(double UpperBoundary) {
    SimpleITKPINVOKE.ThresholdMaximumConnectedComponentsImageFilter_SetUpperBoundary(swigCPtr, UpperBoundary);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetUpperBoundary() {
    double ret = SimpleITKPINVOKE.ThresholdMaximumConnectedComponentsImageFilter_GetUpperBoundary(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetInsideValue(byte InsideValue) {
    SimpleITKPINVOKE.ThresholdMaximumConnectedComponentsImageFilter_SetInsideValue(swigCPtr, InsideValue);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public byte GetInsideValue() {
    byte ret = SimpleITKPINVOKE.ThresholdMaximumConnectedComponentsImageFilter_GetInsideValue(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetOutsideValue(byte OutsideValue) {
    SimpleITKPINVOKE.ThresholdMaximumConnectedComponentsImageFilter_SetOutsideValue(swigCPtr, OutsideValue);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public byte GetOutsideValue() {
    byte ret = SimpleITKPINVOKE.ThresholdMaximumConnectedComponentsImageFilter_GetOutsideValue(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string GetName() {
    string ret = SimpleITKPINVOKE.ThresholdMaximumConnectedComponentsImageFilter_GetName(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string ToString() {
    string ret = SimpleITKPINVOKE.ThresholdMaximumConnectedComponentsImageFilter_ToString(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Image Execute(Image image1) {
    Image ret = new Image(SimpleITKPINVOKE.ThresholdMaximumConnectedComponentsImageFilter_Execute(swigCPtr, Image.getCPtr(image1)), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
