//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace itk.simple {

public class ThresholdSegmentationLevelSetImageFilter : ImageFilter {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal ThresholdSegmentationLevelSetImageFilter(global::System.IntPtr cPtr, bool cMemoryOwn) : base(SimpleITKPINVOKE.ThresholdSegmentationLevelSetImageFilter_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ThresholdSegmentationLevelSetImageFilter obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ThresholdSegmentationLevelSetImageFilter obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SimpleITKPINVOKE.delete_ThresholdSegmentationLevelSetImageFilter(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public ThresholdSegmentationLevelSetImageFilter() : this(SimpleITKPINVOKE.new_ThresholdSegmentationLevelSetImageFilter(), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetLowerThreshold(double LowerThreshold) {
    SimpleITKPINVOKE.ThresholdSegmentationLevelSetImageFilter_SetLowerThreshold(swigCPtr, LowerThreshold);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetLowerThreshold() {
    double ret = SimpleITKPINVOKE.ThresholdSegmentationLevelSetImageFilter_GetLowerThreshold(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetUpperThreshold(double UpperThreshold) {
    SimpleITKPINVOKE.ThresholdSegmentationLevelSetImageFilter_SetUpperThreshold(swigCPtr, UpperThreshold);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetUpperThreshold() {
    double ret = SimpleITKPINVOKE.ThresholdSegmentationLevelSetImageFilter_GetUpperThreshold(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetMaximumRMSError(double MaximumRMSError) {
    SimpleITKPINVOKE.ThresholdSegmentationLevelSetImageFilter_SetMaximumRMSError(swigCPtr, MaximumRMSError);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetMaximumRMSError() {
    double ret = SimpleITKPINVOKE.ThresholdSegmentationLevelSetImageFilter_GetMaximumRMSError(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetPropagationScaling(double PropagationScaling) {
    SimpleITKPINVOKE.ThresholdSegmentationLevelSetImageFilter_SetPropagationScaling(swigCPtr, PropagationScaling);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetPropagationScaling() {
    double ret = SimpleITKPINVOKE.ThresholdSegmentationLevelSetImageFilter_GetPropagationScaling(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetCurvatureScaling(double CurvatureScaling) {
    SimpleITKPINVOKE.ThresholdSegmentationLevelSetImageFilter_SetCurvatureScaling(swigCPtr, CurvatureScaling);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetCurvatureScaling() {
    double ret = SimpleITKPINVOKE.ThresholdSegmentationLevelSetImageFilter_GetCurvatureScaling(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetNumberOfIterations(uint NumberOfIterations) {
    SimpleITKPINVOKE.ThresholdSegmentationLevelSetImageFilter_SetNumberOfIterations(swigCPtr, NumberOfIterations);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint GetNumberOfIterations() {
    uint ret = SimpleITKPINVOKE.ThresholdSegmentationLevelSetImageFilter_GetNumberOfIterations(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetReverseExpansionDirection(bool ReverseExpansionDirection) {
    SimpleITKPINVOKE.ThresholdSegmentationLevelSetImageFilter_SetReverseExpansionDirection(swigCPtr, ReverseExpansionDirection);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void ReverseExpansionDirectionOn() {
    SimpleITKPINVOKE.ThresholdSegmentationLevelSetImageFilter_ReverseExpansionDirectionOn(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public void ReverseExpansionDirectionOff() {
    SimpleITKPINVOKE.ThresholdSegmentationLevelSetImageFilter_ReverseExpansionDirectionOff(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool GetReverseExpansionDirection() {
    bool ret = SimpleITKPINVOKE.ThresholdSegmentationLevelSetImageFilter_GetReverseExpansionDirection(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public uint GetElapsedIterations() {
    uint ret = SimpleITKPINVOKE.ThresholdSegmentationLevelSetImageFilter_GetElapsedIterations(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetRMSChange() {
    double ret = SimpleITKPINVOKE.ThresholdSegmentationLevelSetImageFilter_GetRMSChange(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string GetName() {
    string ret = SimpleITKPINVOKE.ThresholdSegmentationLevelSetImageFilter_GetName(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string ToString() {
    string ret = SimpleITKPINVOKE.ThresholdSegmentationLevelSetImageFilter_ToString(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Image Execute(Image initialImage, Image featureImage) {
    Image ret = new Image(SimpleITKPINVOKE.ThresholdSegmentationLevelSetImageFilter_Execute(swigCPtr, Image.getCPtr(initialImage), Image.getCPtr(featureImage)), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
