//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace itk.simple {

public class Version : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Version(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Version obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Version obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Version() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SimpleITKPINVOKE.delete_Version(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public static uint MajorVersion() {
    uint ret = SimpleITKPINVOKE.Version_MajorVersion();
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static uint MinorVersion() {
    uint ret = SimpleITKPINVOKE.Version_MinorVersion();
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static uint PatchVersion() {
    uint ret = SimpleITKPINVOKE.Version_PatchVersion();
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static uint TweakVersion() {
    uint ret = SimpleITKPINVOKE.Version_TweakVersion();
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string VersionString() {
    string ret = SimpleITKPINVOKE.Version_VersionString();
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string BuildDate() {
    string ret = SimpleITKPINVOKE.Version_BuildDate();
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static uint ITKMajorVersion() {
    uint ret = SimpleITKPINVOKE.Version_ITKMajorVersion();
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static uint ITKMinorVersion() {
    uint ret = SimpleITKPINVOKE.Version_ITKMinorVersion();
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static uint ITKPatchVersion() {
    uint ret = SimpleITKPINVOKE.Version_ITKPatchVersion();
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string ITKVersionString() {
    string ret = SimpleITKPINVOKE.Version_ITKVersionString();
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static VectorString ITKModulesEnabled() {
    VectorString ret = new VectorString(SimpleITKPINVOKE.Version_ITKModulesEnabled(), true);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string ExtendedVersionString() {
    string ret = SimpleITKPINVOKE.Version_ExtendedVersionString();
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string ToString() {
    string ret = SimpleITKPINVOKE.Version_ToString(swigCPtr);
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Version() : this(SimpleITKPINVOKE.new_Version(), true) {
    if (SimpleITKPINVOKE.SWIGPendingException.Pending) throw SimpleITKPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
